# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
set cmd ""
lappend cmd [list source [file join $dir compass_utils.tcl]]
lappend cmd [list lappend ::auto_path $dir]
package ifneeded compass_utils 1.3 [join $cmd ";"]
package ifneeded compass_utils::c 1.1 [list load \
	[file join $dir compass_utils[info sharedlibextension]]]
package ifneeded compass_utils::math 1.1 [list source [file join $dir math.tcl]]
package ifneeded compass_utils::img 1.1 [list load \
	[file join $dir compass_utils_tk[info sharedlibextension]]]
package ifneeded compass_utils::fcgi 1.0 {
    package require compass_utils::c
    cu::fcgi_init
}