# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

set cmdList ""
#lappend cmdList [list source [file join $dir xml2html.tcl]]
lappend cmdList [list source [file join $dir xml2pdf.tcl]]
#lappend cmdList [list source [file join $dir xml2doc.tcl]]

package ifneeded xml2pdf 1.3 [join $cmdList ";"]
package ifneeded drawformulas 1.3 [list source [file join $dir drawformulas.tcl]]