#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es {Could not connect to host '%s' port '%s'} {No se pudo conectar al host '%s' puerto '%s'}
::msgcat::mcset es {Error opening file '%s' (%s)} {Error abriendo el archivo '%s' (%s)}
::msgcat::mcset es {Connection lost. Press here to retry} {Conexión  perdida. Pulse aquí para reintentar}
::msgcat::mcset es {Connection to '%s' is lost} {Se ha perdido la conexión a '%s'}
::msgcat::mcset es {Connection to '%s' is lost. Retry?} {Se ha perdido la conexión a '%s'. Reintentar?}
::msgcat::mcset es Exit Salir
::msgcat::mcset es {GiD geo files} {ficheros geo GiD}
::msgcat::mcset es {All files} Todos
::msgcat::mcset es {Open GiD file} {Abrir fichero GiD}
::msgcat::mcset es {Sending file '%s' (binary=$bin) } {Enviando fichero '%s' (binario=$bin)}
::msgcat::mcset es {Recieving file '%s' (binary=$bin) } {Recibiendo fichero '%s' (binario=$bin)}
::msgcat::mcset es Deiconify Deiconificar
::msgcat::mcset es {Add user} {Añadir usuario}
::msgcat::mcset es User: Usuario:
::msgcat::mcset es Password: Contraseña:
::msgcat::mcset es {Repeat password:} {Repetir contraseña:}
::msgcat::mcset es {User type:} {Tipo de usuario:}
::msgcat::mcset es Administrator Administrador
::msgcat::mcset es Analysis Análisis
::msgcat::mcset es Database {Base de datos}
::msgcat::mcset es {Remove user} {Quitar usuario}
::msgcat::mcset es {Passwords are not equal} {Las contraseñas no son iguales}
::msgcat::mcset es {User cannot be void} {El usuario no puede estar vacio}
::msgcat::mcset es {Enter analysis password} {Introduzca contraseña de análisis}
::msgcat::mcset es {You do not have permissions to store the password} {no tiene permisos para almacenar la contraseña}
::msgcat::mcset es {Are you sure to terminate %d sessions?} {Está seguro de terminar %d sesiones?}
::msgcat::mcset es {Computer memory} {Memoria del ordenador}
::msgcat::mcset es {All processes} {Todos los procesos}
::msgcat::mcset es Memory Memoria
::msgcat::mcset es {Full memory} {Memoria completa}
::msgcat::mcset es {This process} {Este proceso}
::msgcat::mcset es {Total time} {Tiempo total}
::msgcat::mcset es {no process} {Sin proceso}
::msgcat::mcset es {Failed connection to host '%s'} {Falló la conexión al host '%s'}
::msgcat::mcset es {not connected} {no conectado}
::msgcat::mcset es {User or password not OK for host '%s'} {Usuario o contraseña incorrectos para el host '%s'}
::msgcat::mcset es {Connected to host '%s'} {Conectado al host '%s'}
::msgcat::mcset es {Are you sure to unconnect from host '$host' and kill any process?} {Está seguro de desconectarse del host '$host' y finalizar cualquier proceso?}
::msgcat::mcset es {Could not store preferences (%s)} {No se pudieron almacenar las preferencias (%s)}
::msgcat::mcset es {running on' %s'} {Corriendo '%s'}
::msgcat::mcset es {Failed running (%s)} {Fallo al correr (%s)}
::msgcat::mcset es {Compass client} {Cliente Compass}
::msgcat::mcset es Unconnect Desconectado
::msgcat::mcset es Host: Servidor:
::msgcat::mcset es Examples: Ejemplos:
::msgcat::mcset es {Password file:} {Fichero de password:}
::msgcat::mcset es {GiD model:} {modelo GiD}
::msgcat::mcset es {Select a GiD model in browser} {Selecciones un modelo GiD en el  navegador}
::msgcat::mcset es Info Información
::msgcat::mcset es Log Diario
::msgcat::mcset es {Update now} {Actualizar ahora}
::msgcat::mcset es Sessions Sesiones
::msgcat::mcset es {Server management} {Gestión del server}
::msgcat::mcset es {View remote log} {Ver diario remoto}
::msgcat::mcset es {Clear local log} {Limpiar diario local}
::msgcat::mcset es {Server version} {Versión del server}
::msgcat::mcset es Console Consola
::msgcat::mcset es {Add/remove user} {Añadir/quitar usuario}
::msgcat::mcset es {Analysis password} {Contraseña de análisis}
::msgcat::mcset es {Server version: %s} {Versión del server: %s}
::msgcat::mcset es {Could not find tkcon} {No se pudo encontrar tkcon}
::msgcat::mcset es Remote Remoto
::msgcat::mcset es {Attach to remote server} {Adjuntar al server remoto}
::msgcat::mcset es {Welcome to tkcon client console} {Bienvenido a la consola cliente tkcon}
::msgcat::mcset es {Could not find a GiD executable} {No fue posible encontrar un ejecutable de GiD}
::msgcat::mcset es {url does not begin with a known handler like: %s. Proceed?} {el url no empieza con ningún prefijo conocido: %s. ¿Continuar?}
::msgcat::mcset es Warning Atención
::msgcat::mcset es {There are %s message. Delete all of them?} {Hay %s mensajes. Borrar todos?}
::msgcat::mcset es Close Cerrar
::msgcat::mcset es Clear Limpiar
::msgcat::mcset es Save Guardar
::msgcat::mcset es {sqlite files} {ficheros sqlite}
::msgcat::mcset es {Save log} {guardar diario}
::msgcat::mcset es {sqlite3 files} {ficheros sqlite3}
::msgcat::mcset es default {Por defecto}
::msgcat::mcset es {Edit header} {Editar cabecera}
::msgcat::mcset es {Create/edit property} {Crear/editar propiedades}
::msgcat::mcset es Wizard Asistente
::msgcat::mcset es {Delete all} {Borrar todo}
::msgcat::mcset es Edit Editar
::msgcat::mcset es Copy Copiar
::msgcat::mcset es {Insert inside} {Insertar dentro}
::msgcat::mcset es {Insert before} {Insertar antes}
::msgcat::mcset es {Insert after} {Insertar después}
::msgcat::mcset es {Create drawing} {Crear dibujo}
::msgcat::mcset es Delete Borrar
::msgcat::mcset es {Edit drawing} {Editar dibujo}
::msgcat::mcset es {Ramdrawer out of sync (%s)} {Ramdrawer no está sincronizado (%s)}
::msgcat::mcset es Before Antes
::msgcat::mcset es After Después
::msgcat::mcset es Condition: Condición
::msgcat::mcset es {error: name cannot be void} {error: el nombre no puede estar vacío}
::msgcat::mcset es {error: name cannot contain 2 underlines (__)} {error: el nombre no puede contener dos guiones (__)}
::msgcat::mcset es {error: name must begin with a letter and contain letters, numbers or _ or !} {error: el nombre debe comenzar por una letra y contener letras, números o _ o !}
::msgcat::mcset es {error: expression cannot be void} {error: la expresión no puede estar vacía}
::msgcat::mcset es {error: default value for option must be one element of the list} {error: el valor por defecto para la opción debe ser un elemento de la lista}
::msgcat::mcset es {error: value must be a number} {error: el valor debe ser un número}
::msgcat::mcset es {error: name is not correct} {error: el nombre no es correcto}
::msgcat::mcset es {Change header} {Cambiar encabezado}
::msgcat::mcset es Title: Título:
::msgcat::mcset es Description: Descripción
::msgcat::mcset es Arrows Flechas
::msgcat::mcset es {Small arrows} {Flechas pequeñas}
::msgcat::mcset es Notebook {Libro de notas}
::msgcat::mcset es {Pages style:} {Estilo de páginas:}
::msgcat::mcset es {Has set name} {Tiene un set nombre}
::msgcat::mcset es {Sets are a simple way to store groups of values for latter printing in a tabular style} {Los sets son un modo simple de almacenar grupos de valores para imprimir estos últimos en un estilo tabular}
::msgcat::mcset es {Has database} {Tiene base de datos}
::msgcat::mcset es {Database name} {Nombre de la base de datos}
::msgcat::mcset es {Usable in view mode} {Usable in modo vista}
::msgcat::mcset es {Only form in view mode} {Formularios solo en el modo vista}
::msgcat::mcset es {If this option is selected, the notes part of the page is not visualized in view mode} {Si se selecciona esta opción, la parte de notas de la página no se visualiza en el modo vista}
::msgcat::mcset es {It is necessary to enter a title} {Es necesario introducir un título}
::msgcat::mcset es {It is necessary to enter a database name} {Es necesario introducir un nombre para la base de datos}
::msgcat::mcset es {Database name must only contain letters, numbers -_} {El nombre de la base de datos debe contener solo letras, números -_}
::msgcat::mcset es {Do you want to delete database '%s'?} {Desea borrar la base de datos '%s'?}
::msgcat::mcset es {Nothing to delete} {No hay nada para borrar}
::msgcat::mcset es {Are you sure to delete ALL forms information in this page?} {Está seguro de borrar TODA la información de formularios en esta página?}
::msgcat::mcset es {Change properties} {Cambiar propiedades}
::msgcat::mcset es Apply Aplicar
::msgcat::mcset es {property type} {tipo de propiedad}
::msgcat::mcset es Parameter Parámetro
::msgcat::mcset es Condition Condición
::msgcat::mcset es Container Contenedor
::msgcat::mcset es navigate navegar
::msgcat::mcset es Previous Anterior
::msgcat::mcset es Next Siguiente
::msgcat::mcset es {Go to} {Ir a}
::msgcat::mcset es Action Acción
::msgcat::mcset es New Nuevo
::msgcat::mcset es {Update current} {Actualizar actual}
::msgcat::mcset es Refresh Refrescar
::msgcat::mcset es properties propiedades
::msgcat::mcset es Location: Situación:
::msgcat::mcset es {Same page} {La misma página}
::msgcat::mcset es Name: Nombre:
::msgcat::mcset es {Do you want to rename field?} {Desea renombrar el campo?}
::msgcat::mcset es {Short name:} {Nombre corto:}
::msgcat::mcset es {Print name:} {Nombre a mostrar:}
::msgcat::mcset es numeric numérico
::msgcat::mcset es text texto
::msgcat::mcset es expression expresión
::msgcat::mcset es {text expression} {expresión texto}
::msgcat::mcset es {options editable} {opciones editables}
::msgcat::mcset es {options non-editable} {opciones no editables}
::msgcat::mcset es formatted {con formato}
::msgcat::mcset es {formatted expression} {expresión con formato}
::msgcat::mcset es button botón
::msgcat::mcset es date fecha
::msgcat::mcset es {Field type:} {Campo tipo:}
::msgcat::mcset es Values: Valores:
::msgcat::mcset es {Enter a comma separator list of values here} {Introduzca una coma separador de lista de valores aquí}
::msgcat::mcset es Value: Valor:
::msgcat::mcset es Expression: Expresión:
::msgcat::mcset es Command: Comando:
::msgcat::mcset es {Examples:
\t%s} {Ejemplos:
\t%s}
::msgcat::mcset es Units: Unidades:
::msgcat::mcset es {True text:} {Texto 'cierto'}
::msgcat::mcset es {False text:} {Texto 'falso':}
::msgcat::mcset es Help Ayuda
::msgcat::mcset es {Start page} {Página de inicio}
::msgcat::mcset es {Previous page} {Página anterior}
::msgcat::mcset es {Next page} {Página siguiente}
::msgcat::mcset es {Last page} {Última página}
::msgcat::mcset es Go Ir
::msgcat::mcset es Start Inicio
::msgcat::mcset es Last Último
::msgcat::mcset es {Search in field} {Buscar en el campo}
::msgcat::mcset es {Search in any field} {Buscar en cualquier campo}
::msgcat::mcset es {Create new row} {Crear una nueva fila}
::msgcat::mcset es {Modify selected row} {Modificar la fila seleccionada}
::msgcat::mcset es {Find rows by entering text in fields} {Encontrar filas introduciendo texto en campos}
::msgcat::mcset es {Delete selected rows} {Borrar la fila seleccionada}
::msgcat::mcset es List Listar
::msgcat::mcset es {It is necessary to select one row in order to modify it} {Es necesario seleccionar una fila para modificarla}
::msgcat::mcset es {It is necessary to select only one row in order to modify it} {Es necesario elegir solo una fila para modificarla}
::msgcat::mcset es {It is necessary to select rows in order to delete them} {Es necesario seleccionar filas para borrarlas}
::msgcat::mcset es {Are you sure to delete %d rows?} {Está seguro de borrar %d filas?}
::msgcat::mcset es search buscar
::msgcat::mcset es Search Buscar
::msgcat::mcset es {Search text} {Buscar texto}
::msgcat::mcset es {Close search window} {Cerrar la ventana de búsqueda}
::msgcat::mcset es {Enter the search text in any of the fields} {Introduzca el texto a buscar en cualquiera de los campos}
::msgcat::mcset es {SQL table schema} {Esquema tabla SQL}
::msgcat::mcset es Intro Intro
::msgcat::mcset es {Update values (Return)} {Actualizar valores (Return)}
::msgcat::mcset es {Set name:} {Nombre del Set:}
::msgcat::mcset es {A set name is a way to store a group of values and results for later tabular printing} {Un Nombre de set es una forma de almacenar un grupo de valores y resultados para una posterior impresión tabular}
::msgcat::mcset es {Create new set} {Crear un nuevo set}
::msgcat::mcset es Print Imprimir
::msgcat::mcset es {Print all} {Imprimir todo}
::msgcat::mcset es {Print none} {Imprimir nada}
::msgcat::mcset es {Sets can only be modified in edit page mode} {Los sets solo pueden ser modificados en modo de edición de página}
::msgcat::mcset es {Step %d} {Paso %d}
::msgcat::mcset es {Use contextual menu (right button mouse) over the field elements in order to modify this form} {Use el menú contextual (botón derecho del ratón) sobre los elementos del campo para modificar este formulario}
::msgcat::mcset es {Select color} {Seleccionar el color}
::msgcat::mcset es {Initial value} {Valor inicial}
::msgcat::mcset es {Default value} {Valor por defecto}
::msgcat::mcset es {Select file} {Seleccionar fichero}
::msgcat::mcset es View/execute Ver/ejecutar
::msgcat::mcset es {Extract in '%s'} {Extraer en '%s'}
::msgcat::mcset es {Extract in ...} {Extraer en ...}
::msgcat::mcset es Ramviewer Ramviewer
::msgcat::mcset es {error in container '%s'. Condition not ok} {error en el contenedor '%s'. La condición no es correcta}
::msgcat::mcset es !ERROR !ERROR
::msgcat::mcset es OK#C#Valid Válido
::msgcat::mcset es {Fail#C#No Valid} {No válido}
::msgcat::mcset es {Choose Color} {Elija color}
::msgcat::mcset es {Load file} {Cargar fichero}
::msgcat::mcset es {Could not open RamViewer (%s)} {No se pudo abrir RamViewer (%s)}
::msgcat::mcset es {File: %s
} {Fichero: %s
}
::msgcat::mcset es {Size: $sizep
} {Tamaño: $sizep
}
::msgcat::mcset es {There is no file to extract} {No hay fichero a extraer}
::msgcat::mcset es {Save file} {Salvar fichero}
::msgcat::mcset es {File '%s' exists. Overwrite?} {El fichero '%s' existe. ¿Sobrescribirlo?}
::msgcat::mcset es {error: %s} {error: %s}
::msgcat::mcset es {Saved file in '%s'} {Fichero guardado en '%s'}
::msgcat::mcset es {Set %s} {Set %s}
::msgcat::mcset es {error: field '%s' not correct value='%s'} {error: campo '%s' incorrecto valor='%s'}
::msgcat::mcset es {error in field '%s' not valid value '%s'} {error en campo '%s' valor inválido '%s'}
::msgcat::mcset es {Form type} {Formulario tipo}
::msgcat::mcset es {Import data} {Importar datos}
::msgcat::mcset es {Create form fields} {Crear campos de formulario}
::msgcat::mcset es {Form created} {Formulario creado}
::msgcat::mcset es {Welcome to the forms creation wizard. Select what kind of form do you wish to create} {Bienvenido al asistente de creación de formularios. Seleccione qué tipo de formulario desea crear}
::msgcat::mcset es {A set of fields where to enter values and formulas} {Un conjunto de campos dónde introducir valores y fórmulas}
::msgcat::mcset es {A form, to store values in a database} {Un formulario, para almacenar valores en una base de datos}
::msgcat::mcset es {Enter fields definition manually} {introduzca la definición de los campos manualmente}
::msgcat::mcset es {Import from Spreadsheet (Excel or OpenOffice)} {Importar desde una hoja de cálculo (Excel u OpenOffice)}
::msgcat::mcset es {Variable names on the left} {Nombres de variables a la izquierda}
::msgcat::mcset es {View Spreadsheet variable names} {Ver nombres de variables de la Hoja de cálculo}
::msgcat::mcset es {Variable names above} {Nombres de variables arriba}
::msgcat::mcset es {Variable names above the table rows} {Nombres de variables sobre las filas de la tabla}
::msgcat::mcset es {Spreadsheet file} {Fichero de Hoja de cálculo}
::msgcat::mcset es {There has been an error when importing the Spreadsheet file (%s)} {Hubo un error al importar el fichero de Hoja de cálculo (%s)}
::msgcat::mcset es {Add fields to the form} {Añadir campos al formulario}
::msgcat::mcset es Name Nombre
::msgcat::mcset es type tipo
::msgcat::mcset es Group Grupo
::msgcat::mcset es {Field name} {Nombre del campo}
::msgcat::mcset es {default value} {valor por defecto}
::msgcat::mcset es Number Número
::msgcat::mcset es Expression Expresión
::msgcat::mcset es Add Añadir
::msgcat::mcset es {Add a new field to the form} {Añadir un nuevo campo al formulario}
::msgcat::mcset es Remove Quitar
::msgcat::mcset es {Remove the selected field from the list} {Quitar el campo seleccionado de la lista}
::msgcat::mcset es More Más
::msgcat::mcset es {Add new field in new group} {Añadir nuevo campo en nuevo grupo}
::msgcat::mcset es {Delete all fields} {Borrar todos los campos}
::msgcat::mcset es {It has not been possible to import any field from the Spreadsheet file} {No ha sido posible importar ningún campo desde el fichero de Hoja de cálculo}
::msgcat::mcset es {No field has been created} {No se ha creado ningún campo}
::msgcat::mcset es {A new form has been created with %d fields} {Ha sido creado un nuevo formulario con %d campos}
::msgcat::mcset es {A new form has been created with %d fields. %d rows have been imported} {Ha sido creado un nuevo formulario con %d campos, %d filas se han importado}
::msgcat::mcset es {You can modify any field in the form by right-clicking the mouse over it} {Puede modificar cualquier campo en el formulario haciendo click con el botón derecho del ratón sobre él}
::msgcat::mcset es {You can try with a new Spreadsheet file by pressing button 'Previous'} {Puede probar con un nuevo fichero de Hoja de Cálculo pulsando el botón 'Previo'}
::msgcat::mcset es {You can add new fields by pressing button 'Previous'} {Puede añadir nuevos campos pulsando el botón 'Previo'}
::msgcat::mcset es {Group %d} {Grupo %d}
::msgcat::mcset es {Select group} {Seleccionar grupo}
::msgcat::mcset es {Enter the name for the group where the field will be inserted:} {Introduzca el nombre del grupo donde se insertará el campo:}
::msgcat::mcset es {It is necessary to enter a field name} {Se necesita introducir un nombre de campo}
::msgcat::mcset es {A field with this name already exists} {Ya existe un campo con ese nombre}
::msgcat::mcset es {Spreadsheet files} {Ficheros de Hoja de cálculo}
::msgcat::mcset es {Import Spreadsheet file} {Importar fichero de Hoja de cálculo}
::msgcat::mcset es {It is necessary to have Excel installed in the computer. Try to import format XML-2003 or XLSX or ODS} {Se necesita tener Excel instalado en el ordenador. Intente importar el formato XML-2003 o XLSX o ODS}
::msgcat::mcset es Today Hoy
::msgcat::mcset es {starting server (version %s)} {Iniciando servidor (versión  %s)}
::msgcat::mcset es {Exiting server} {saliendo de servidor}
::msgcat::mcset es {Auto finished session %s-%s-%s-%s} {Sesión finalizada automáticamente %s-%s-%s-%s}
::msgcat::mcset es {Error restarting session '%s' (%s)} {Error reiniciando sesión '%s' (%s)}
::msgcat::mcset es {Auto restarted session %s-%s-%s-%s} {Sesión reiniciada automáticamente %s-%s-%s-%s}
::msgcat::mcset es {Lost session %s-%s-%s-%s} {Sesión perdida %s-%s-%s-%s}
::msgcat::mcset es {Ended session %s-%s-%s-%s} {Sesión terminada %s-%s-%s-%s}
::msgcat::mcset es {rejected connection} {Conexión rechazada}
::msgcat::mcset es {rejected connection from '%s' user '%s' user_type '%s'. bad username/password} {conexión rechazada desde '%s' usuario '%s' tipo_de_usuario '%s'. Mal nombre de usuario/contraseña}
::msgcat::mcset es {rejected connection. bad username/password} {Conexión rechazada. Mal nombre de usuario/contraseña}
::msgcat::mcset es {rejected connection. session does not exist} {Conexión rechazada. No existe sesión}
::msgcat::mcset es {reconnected to session '%s'} {Reconectado a sesión '%s'}
::msgcat::mcset es {accepted connection from '%s' user '%s' type '%s'. Created session '%s'} {conexión aceptada desde '%s' usuario '%s' tipo '%s'. Creada sesión '%s'}
::msgcat::mcset es {Compass server} {Servidor Compass}
::msgcat::mcset es {Clear log} {Limpiar diario}
::msgcat::mcset es {View log} {Ver diario}
::msgcat::mcset es Hide Ocultar
::msgcat::mcset es {Started server at port %s} {Servidor iniciado en puerto %s}
::msgcat::mcset es {Compass server (port: %s)} {Servidor Compass (puerto: %s)}
::msgcat::mcset es {starting icon try} {Iniciando bandeja de icono}
::msgcat::mcset es {Added user '%s', type='%s'} {Añadido usuario '%s', type='%s'}
::msgcat::mcset es {Removed user '%s' type '%s'} {Quitado usuario '%s' tipo '%s'}
::msgcat::mcset es {Creating directory '%s'} {Creando directorio '%s'}
::msgcat::mcset es {killed process %s} {Proceso eliminado %s}
::msgcat::mcset es {recieving file '%s'} {recibiendo fichero '%s'}
::msgcat::mcset es {recieved file} {fichero recibido}
::msgcat::mcset es {sending file '%s'} {enviando fichero '%s'}
::msgcat::mcset es {failed sending file '%s'} {fallo enviando fichero '%s'}
::msgcat::mcset es {Requesting sessions list} {Solicitando lista de sesiones}
::msgcat::mcset es Id Identificar
::msgcat::mcset es Username {Nombre de usuario}
::msgcat::mcset es Type Tipo
::msgcat::mcset es Connection Conexión
::msgcat::mcset es Active Activo
::msgcat::mcset es Date Fecha
::msgcat::mcset es Directories Directorios
::msgcat::mcset es Processes Procesos
::msgcat::mcset es {Requesting processes info} {Solicitando información de procesos}
::msgcat::mcset es {error: File '%s' is not a directory} {error: Fichero '%s' no es un directorio}
::msgcat::mcset es {error: File '%s' does not exist} {error: Fichero '%s' no existe}
::msgcat::mcset es {Installing on computer '%s'} {Instalando en el ordenador '%s'}
::msgcat::mcset es {Error connecting to computer '%s' with user '%s'} {Error conectando al ordenador '%s' con el usuario '%s'}
::msgcat::mcset es {Copied files to computer '%s'} {Ficheros copiados al ordenador '%s'}
::msgcat::mcset es {Started service on computer '%s'} {Servicio iniciado en el ordenador '%s'}
::msgcat::mcset es {Going to connect (%s) to computer '%s'} {Va a conectar (%s) al ordenador '%s'}
::msgcat::mcset es {Installed on computer '%s'} {Instalado en el ordenador '%s'}
::msgcat::mcset es {Install Compass server} {Instalar servidor Compass}
::msgcat::mcset es Computer Ordenador
::msgcat::mcset es Computer: Ordenador:
::msgcat::mcset es {A list of one or more computers. Examples:} {Una lista de uno o más ordenadores. Ejemplos:}
::msgcat::mcset es {Destination base dir:} {Destinación base dir:}
::msgcat::mcset es {This directory must exist} {Este directorio debe existir}
::msgcat::mcset es Server Servidor
::msgcat::mcset es {Copy local users} {Copiar usuarios locales}
::msgcat::mcset es {Service installed and running} {Servicio instalado y corriendo}
::msgcat::mcset es Icons Iconos
::msgcat::mcset es Database: {Base de datos:}
::msgcat::mcset es and y
::msgcat::mcset es or o
::msgcat::mcset es {Draw name} {dibujar nombre}
::msgcat::mcset es Search: Buscar
::msgcat::mcset es {Draw icons} {Dibujar iconos}
::msgcat::mcset es {Open new view} {Abrir nueva vista}
::msgcat::mcset es {Drop here icons for deleting them from database} {Soltar aquí los iconos para borrarlos de la base de datos}
::msgcat::mcset es {Database '%s' does not exist} {La base de datos '%s' no existe}
::msgcat::mcset es {Open database} {Abrir base de datos}
::msgcat::mcset es {user defined} {Definido por el usuario}
::msgcat::mcset es {GIF files} {ficheros GIF}
::msgcat::mcset es {Add icon} {Añadir icono}
::msgcat::mcset es {Icon name:} {Nombre del icono:}
::msgcat::mcset es {Overwrite existing icon with same name} {Sobrescribir el icono existente con el mismo nombre}
::msgcat::mcset es Collection: Colección:
::msgcat::mcset es Groups: Grupos:
::msgcat::mcset es {Are you sure to delete icon '%s'?} {Está seguro de borrar el icono '%s'?}
::msgcat::mcset es {Add icon...} {Añadir icono...}
::msgcat::mcset es {Copy name} {Copiar nombre}
::msgcat::mcset es {Copy command name} {Copiar nombre de comando}
::msgcat::mcset es {Save as...} {Salvar como...}
::msgcat::mcset es {Copy create cmd} {Copiar crear cmd}
::msgcat::mcset es Paste Pegar
::msgcat::mcset es {Delete icon} {Borrar icono}
::msgcat::mcset es {Drawing %d items} {Dibujando %d items}
::msgcat::mcset es {It is necessary to have ImageMagick installed for converting images} {Es necesario tener instalado ImageMagick para poder convertir las imágenes}
::msgcat::mcset es {Sysinfo data not correct (data='%s')} {Datos del sysinfo incorrectos (data='%s')}
::msgcat::mcset es Yes Sí
::msgcat::mcset es {Yes to all} {Sí a todo}
::msgcat::mcset es {No to all} {No a todo}
::msgcat::mcset es {Are you sure to overwrite file '%s'?} {Está seguro de sobrescribir el fichero '%s'?}
::msgcat::mcset es {Form properties} {Propiedades del formulario}
::msgcat::mcset es {Delete form} {Borrar formulario}
::msgcat::mcset es {Create/edit fields} {Crear/editar campos}
::msgcat::mcset es {Edit field} {Editar campo}
::msgcat::mcset es {Copy field} {Copiar campo}
::msgcat::mcset es {Insert field inside} {Insertar campo dentro}
::msgcat::mcset es {Insert field before} {Insertar campo antes}
::msgcat::mcset es {Insert field after} {Insertar campo después}
::msgcat::mcset es {Delete field} {Borrar campo}
::msgcat::mcset es {error: name must begin with a letter and contain letters, numbers spaces or _ or !} {error: el nombre debe empezar con una letra y contener letras, números o _ o !}
::msgcat::mcset es {Identifier '%s' is not allowed for a field name} {El identificador '%s' no está permitido para un nombre de campo}
::msgcat::mcset es {There is already a field with name '%s'. Overwrite?} {Ya hay un campo con el nombre '%s'. Sobrescribir?}
::msgcat::mcset es title título
::msgcat::mcset es Title Título
::msgcat::mcset es Description Descripción
::msgcat::mcset es {form type} {de tipo}
::msgcat::mcset es {No database} {Ninguna base de datos}
::msgcat::mcset es {The form has no associated database. Formulas can be evaluated but results sets cannot be stored} {El formulario no tiene asociada una base de datos. Pueden ser evaluadas las fórmulas, pero los resultados no se almacenarán.}
::msgcat::mcset es {The form has one associated database. Sets of values can be stored by the form user in view mode} {El formulario tiene una base de datos asociada. El set de valores pueden guardarse por el usuario del formulario en el modo de vista}
::msgcat::mcset es {Has database with named entries} {Tiene base de datos con entradas nombradas}
::msgcat::mcset es {The form has one associated database. Every stored set of values will have a name} {El formulario tiene una base de datos asociada. Cada set de valores guardados tendrá un nombre}
::msgcat::mcset es {database details} {Detalle de la base de datos}
::msgcat::mcset es Automatic Automático
::msgcat::mcset es {Hide notes in view mode} {Esconder notas en el modo vista}
::msgcat::mcset es {form style} {estilo del formulario}
::msgcat::mcset es List#C#Noun Lista
::msgcat::mcset es Buttons Botones
::msgcat::mcset es {Normal size} {Tamaño normal}
::msgcat::mcset es {Small size} {Tamaño pequeño}
::msgcat::mcset es Pages Páginas
::msgcat::mcset es {Form pages} {Páginas del formulario}
::msgcat::mcset es {Select the form page} {Seleccione la página del formulario}
::msgcat::mcset es {Name id} {Nombre id}
::msgcat::mcset es {New entry} {Nueva entrada}
::msgcat::mcset es {Modify entry} {Modificar entrada}
::msgcat::mcset es {Search in name} {Buscar en nombre}
::msgcat::mcset es {View form and database} {Ver formulario y base de datos}
::msgcat::mcset es {View database list} {Ver lista de base de datos}
::msgcat::mcset es {View form} {Ver formulario}
::msgcat::mcset es {Delete entries} {Borrar entradas}
::msgcat::mcset es {Enter the name of the entry to create or modify} {Introducir el nombre de la entrada a crear o modificar}
::msgcat::mcset es {Create new entry in the database} {Crear la nueva entrada en la base de datos}
::msgcat::mcset es {Modify selected entry in the databse} {Modificar la entrada seleccionada en la base de datos}
::msgcat::mcset es {Search database} {Buscar base de datos}
::msgcat::mcset es {Additional commands} {Comandos adicionales}
::msgcat::mcset es Page Página
::msgcat::mcset es {Database List} {Lista de base de datos}
::msgcat::mcset es {It is necessary to enter a name for the new entry} {Es necesario introducir un nombre para la nueva entrada}
::msgcat::mcset es {It is necessary to enter the name of the entry to be modified} {Es necesario introducir el nombre de la entrada a modificar}
::msgcat::mcset es {There is already one entry with name '%s'. Modify it?} {Ya hay una entrada con el nombre '%s'. Desea modificarla?}
::msgcat::mcset es {There is no entry with name '%s'. It cannot be modified} {No hay entrada con el nombre '%s'. No puede modificarse}
::msgcat::mcset es {It is necessary to select one entry in order to modify it} {Es necesario seleccionar una entrada para modificarla}
::msgcat::mcset es {It is necessary to select only one entry in order to modify it} {Es necesario seleccionar solo una entrada para modificarla}
::msgcat::mcset es {Created new entry with name '%s'} {Creada nueva entrada con nombre '%s'}
::msgcat::mcset es {Modified entry with name '%s'} {Entrada modificado con nombre '%s'}
::msgcat::mcset es {Created new entry} {Creada nueva entrada}
::msgcat::mcset es {Updated selected entry} {Actualizada entrada seleccionada}
::msgcat::mcset es {There are no entries that fullfill this search criteria} {No hay entradas que cumplan ese criterio de búsqueda}
::msgcat::mcset es {It is necessary to select one entry in order to get its values} {Es necesario seleccionar una entrada para obtener su valores}
::msgcat::mcset es {There are %d entries that fullfill this search criteria} {Hay %d entradas que cumplen este criterio de búsqueda}
::msgcat::mcset es {It is necessary to select only one entry in order to get its values} {Es necesario seleccionar solo una entrada para obtener sus valores}
::msgcat::mcset es {It is necessary to select one or more entries in order to delete them} {Es necesario seleccionar una o más entradas para borrarlas}
::msgcat::mcset es {It is necessary to enter a name for deleting its entry} {Es necesario introducir un nombre para borrar su entrada}
::msgcat::mcset es {Entry with name '%s' does not exist in the database} {La entrada con nombre '%s' no existe en la base de datos}
::msgcat::mcset es {Are you sure to delete entry '%s'?} {Está seguro de borrar la entrada '%s'?}
::msgcat::mcset es {Are you sure to delete one entry?} {Está seguro de borrar una entrada?}
::msgcat::mcset es {Are you sure to delete %d entries?} {Está seguro de borrar %d entradas?}
::msgcat::mcset es {Select file (examples directory)} {Seleccione fichero (directorio ejemplos)}
::msgcat::mcset es Reload Recargar
::msgcat::mcset es {There is no image to view} {No hay imagen que visualizar}
::msgcat::mcset es {Values by color} {Valores por color}
::msgcat::mcset es {Delete existing fields} {Borrar campos existentes}
::msgcat::mcset es Note Nota
::msgcat::mcset es {All fields need to be contained in one group. There can exist one or more groups} {Todos los campos necesitan estar contenidos en un grupo. Pueden existir uno o más grupos}
::msgcat::mcset es {It is necessary to enter a group name} {Es necesario introducir un nombre de grupo}
::msgcat::mcset es popt popt
::msgcat::mcset es {unknown errno} {unknown errno}
::msgcat::mcset es {option type (%d) not implemented in popt
} {option type (%d) not implemented in popt
}
::msgcat::mcset es {missing argument} {missing argument}
::msgcat::mcset es {unknown option} {unknown option}
::msgcat::mcset es {aliases nested too deeply} {aliases nested too deeply}
::msgcat::mcset es {error in paramter quoting} {error in paramter quoting}
::msgcat::mcset es {invalid numeric value} {invalid numeric value}
::msgcat::mcset es {number too large or too small} {number too large or too small}
::msgcat::mcset es {unknown error} {error desconocido}
::msgcat::mcset es {Show this help message} {Muestra este mensaje de ayuda}
::msgcat::mcset es {Display brief usage message} {  Visualiza un breve uso del mensaje}
::msgcat::mcset es ARG ARG
::msgcat::mcset es Usage: Uso:
::msgcat::mcset es {[OPTION...]} {[OPCION...]}
::msgcat::mcset es {Find executable for '%s'} {Encontrar ejecutable para '%s'}
::msgcat::mcset es {Executable file} {Fichero ejecutable}
::msgcat::mcset es {TCL files} {Ficheros TCL}
::msgcat::mcset es {Find RamDebugger.tcl} {Encontrar RamDebugger.tcl}
::msgcat::mcset es {Open RamDebugger} {Abrir RamDebugger.tcl}
::msgcat::mcset es {RamDebugger cannot be open. It can be installed from http://www.compassis.com/ramdebugger.} {No puede abrirse RamDebugger. Puede instalarlo desde http://www.compassis.com/ramdebugger.}
::msgcat::mcset es {Do you want to find it manually (RamDebugger.tcl)?} {Desea encontrarlo manualmente (RamDebugger.tcl)?}
::msgcat::mcset es File Fichero
::msgcat::mcset es {RamDebugger not found} {RamDebugger no encontrado}
::msgcat::mcset es {[$node @pn } {[$node @pn}
::msgcat::mcset es {Import from other forms} {Importar desde otros formularios}
::msgcat::mcset es {Edit field '%s'} {Editar campo '%s'}
::msgcat::mcset es {Edit container '%s'} {Editar contenedor '%s'}
::msgcat::mcset es {Same line} {Misma línea}
::msgcat::mcset es {Same menu} {Mismo menú}
::msgcat::mcset es {Lognoter help:} {Ayuda Lognoter:}
::msgcat::mcset es {Use a page of current lognoter database for help} {Use una página de la actual base de datos de Lognoter para ayuda.}
::msgcat::mcset es {display style} {Mostrar estilo}
::msgcat::mcset es {Small buttons} {Botones pequeños}
::msgcat::mcset es {Detailed formulas} {Fórmulas detalladas}
::msgcat::mcset es Never Nunca
::msgcat::mcset es {When editing} {Al editar}
::msgcat::mcset es {In forms} {En formularios}
::msgcat::mcset es {In print} {En impresión}
::msgcat::mcset es Always Siempre
::msgcat::mcset es {print options} {opciones de impresión}
::msgcat::mcset es {For first data set} {Para el primer set de datos}
::msgcat::mcset es {Print detailed form} {Imprimir formulario detallado}
::msgcat::mcset es {For all data sets} {Para todos los sets de datos}
::msgcat::mcset es {Print table} {Imprimir tabla}
::msgcat::mcset es {Do not print} {No imprimir}
::msgcat::mcset es Import Importar
::msgcat::mcset es {Select form} {Seleccionar formulario}
::msgcat::mcset es Entry Entrada
::msgcat::mcset es {Page is not a correct form} {La página no es un formulario correcto}
::msgcat::mcset es {Entry is not correct} {La entrada no es correcta}
::msgcat::mcset es {Select page} {Seleccione página}
::msgcat::mcset es {Clear from list} {Limpiar de la lista}
::msgcat::mcset es {Page '%s' is not a correct form} {La página '%s' no es un formulario correcto}
::msgcat::mcset es {Do you want to delete existing table '%s'?} {Desea borrar la tabla existente '%s'?}
::msgcat::mcset es {Are you sure to delete internal database for page '%s'?} {Está seguro de borrar la base de datos interna para la página '%s'?}
::msgcat::mcset es {Are you sure to delete internal database for current page?} {Está seguro de borrar la base de datos para la página actual?}
::msgcat::mcset es {Do you want to delete database '%s' associated to page '%s'?} {Desea borrar la base de datos '%s' asociada a la página '%s'?}
::msgcat::mcset es {Do you want to delete database '%s' associated to current page?} {Desea borrar la base de datos '%s' asociada a la actual página?}
::msgcat::mcset es {Are you sure to delete all forms information in this page?} {Está seguro de borrar toda la información de los formularios en esta página?}
::msgcat::mcset es {Report maker} {Creador de informes}
::msgcat::mcset es {If condition evaluate to false or 0, field or container will be disabled.
Examples:
\t%s} {Si la condición  es falsa o 0, el campo o contenedor será deshabilitado.
Ejemplos:

t%s}
::msgcat::mcset es {Show database list} {Mostrar la lista de base de datos}
::msgcat::mcset es {Hide database list} {Esconder lista de base de datos}
::msgcat::mcset es {The form has changes in its values. Do you want to proceed and loose any modifications?} {El formulario tiene cambios en sus valores. Quiere proceder y perder cualquier modificación?}
::msgcat::mcset es {Press here to see the entries} {Pulse aquí para ver las entradas}
::msgcat::mcset es letters letras
::msgcat::mcset es {Select all} {Seleccionar todo}
::msgcat::mcset es First Primero
::msgcat::mcset es {Move entry to %s} {Mover entrada a %s}
::msgcat::mcset es {Edit subtree '%s'} {Editar subárbol '%s'}
::msgcat::mcset es {Data cannot be saved. It is out of sync} {No pueden guardarse los datos. Fuera de sincronización}
::msgcat::mcset es {Data cannot be saved. It is not correct} {No pueden guardarse los datos. No son correctos}
::msgcat::mcset es {Data cannot be saved. It is not valid XML ($newNode)} {No pueden guardarse los datos. No es un XML válido ($newNode)}
::msgcat::mcset es {Data cannot be saved. It is not OK} {No pueden guardarse los datos. Incorrectos.}
::msgcat::mcset es {Actualize formulae values (Return)} {Actualizar los valores de formula (Return)}
::msgcat::mcset es Actualize Actualizar
::msgcat::mcset es {Import data from other forms} {Importar datos desde otros formularios}
::msgcat::mcset es {It is not possible to visualize help for page '%s'} {No es posible visualizar la ayuda para la página '%s'}
::msgcat::mcset es {error in field '%s'. Condition not ok} {Error en el campo '%s'. Condición incorrecta}
::msgcat::mcset es {I shall create it by myself} {Lo crearé yo mismo}
::msgcat::mcset es Numeric Numérico
::msgcat::mcset es {Edit the selected field of the form} {Editar el campo seleccionado del formulario}
::msgcat::mcset es {Add new field in new container} {Añadir un nuevo campo en el nuevo contenedor}
::msgcat::mcset es {Edit field in new container} {Editar campo en el nuevo contenedor}
::msgcat::mcset es {It is necessary to select one field in the list} {Se necesita seleccionar un campo en la lista}
::msgcat::mcset es {Container %d} {Contenedor %d}
::msgcat::mcset es {Select container} {Seleccione contenedor}
::msgcat::mcset es {Enter the name for the container where the field will be inserted:} {Introduzca el nombre para el contenedor donde se insertará el campo:}
::msgcat::mcset es {All fields need to be contained in one container. There can exist one or more containers} {Todos los campos necesitan estar dentro de un contenedor. Pueden existir uno o más contenedores.}
::msgcat::mcset es {It is necessary to enter a container name} {Es necesario introducir un nombre de contenedor}
::msgcat::mcset es {The value for a numeric field needs to be a number} {El valor para un campo numérico debe ser un número.}
::msgcat::mcset es {The value for a expression field cannot be void} {El valor para un campo de expresión no puede estar vacio}
::msgcat::mcset es {It is necessary to enter a file name} {Es necesario introducir un nombre de fichero.}
::msgcat::mcset es {File '%s' does not exist} {El fichero '%s' no existe.}
::msgcat::mcset es OK Aceptar
::msgcat::mcset es Cancel Cancelar
::msgcat::mcset es {Select the page} {Seleccione la página}
::msgcat::mcset es {Add title page} {Añadir página de título}
::msgcat::mcset es {Add normal page} {Añadir página normal}
::msgcat::mcset es {Page %d} {Página %d}
::msgcat::mcset es Cut Cortar
::msgcat::mcset es (Clear) (Limpiar)
::msgcat::mcset es Rename Renombrar
::msgcat::mcset es Unnamed%d {Sin nombre%d}
::msgcat::mcset es {Name can only contain letters, digits, -_.'} {El nombre solo puede contener letras, dígitos, -_.'}
::msgcat::mcset es {Print formulas} {Imprimir fórmulas}
::msgcat::mcset es No No
::msgcat::mcset es {Detailed when edit} {Detallado con edición}
::msgcat::mcset es Detailed Detallado
::msgcat::mcset es {Do you want to reload file '%s'?} {Desea recargar el archivo '%s'?}
::msgcat::mcset es {Creation date} {Fecha de creación}
::msgcat::mcset es {Modification date} {Fecha de modificación}
::msgcat::mcset es {View columns at maximum width} {Ver columnas al ancgho máximo}
::msgcat::mcset es {Modify some fields} {Modificar algunos campos}
::msgcat::mcset es {Modify selected entry in the database} {Modificar las entradas elegidas en la base de datos}
::msgcat::mcset es {Select fields to update} {Seleccione campos a actualizar}
::msgcat::mcset es {Select fields to update (Modifying %d entries)} {Seleccione campos a actualizar (Modificando %d entradas)}
::msgcat::mcset es {Updated %d selected entries} {Actualizar %d entradas elegidas}
::msgcat::mcset es {View dates} {Ver fechas}
::msgcat::mcset es {Move entry to} {Modificar entrada a}
::msgcat::mcset es {Reorder ids} {Reordenar ids}
::msgcat::mcset es {Pasted data is not correct (# columns=%d). In needs to have %d or %d columns or have a header with some column names} {Los datos pegados no son correctos (# columnas=%d). Es necesario tener %d ó %d columnas o un encabezamiento con algunos nombres de columnas}
::msgcat::mcset es {Are you sure to add %d entries to current database?} {Está seguro de añadir %d entradas a la actual base de datos?}
::msgcat::mcset es {Error pasting data (%s)} {Error pegando datos (%s)}
::msgcat::mcset es {First quarter} {Primer Trimestre}
::msgcat::mcset es {Second quarter} {Segundo Trimestre}
::msgcat::mcset es {Third quarter} {Tercer Trimestre}
::msgcat::mcset es {Forth quarter} {Cuarto Trimestre}
::msgcat::mcset es {Full year} {Año completo}
::msgcat::mcset es {User defined} {Def. usuario}
::msgcat::mcset es {Enter time period} {Introduzca el período de tiempo}
::msgcat::mcset es {time period} {periodo de tiempo}
::msgcat::mcset es time tiempo
::msgcat::mcset es Period Periodo
::msgcat::mcset es Dates Fechas
::msgcat::mcset es From De
::msgcat::mcset es To A
::msgcat::mcset es {print template} {Imprimir plantilla}
::msgcat::mcset es Template Plantilla
::msgcat::mcset es {print detail} {Imprimir detalles}
::msgcat::mcset es {Print detailed data} {Imprimir información detallada}
::msgcat::mcset es {SQL condition} {Condición SQL}
::msgcat::mcset es {Dates are not OK} {Las fechas no son correctas}
::msgcat::mcset es {Error: table '%s' does not exist} {Error: tabla '%s' no existe}
::msgcat::mcset es {User is not allowed to add/modify other users} {El usuario no tiene permiso para añadir/modificar otros usuarios}
::msgcat::mcset es Update Actualizar
::msgcat::mcset es {Clear search entry} {Limpiar la entrada de búsqueda}
::msgcat::mcset es {Stop server} {Parar servidor}
::msgcat::mcset es {starting session for user '%s'} {Iniciando sesión para usuario '%s'}
::msgcat::mcset es {Administrative user and password} {Usuario administrador y password}
::msgcat::mcset es {Enter administrative user and password:} {Introduzca un usuario administrador y el password}
::msgcat::mcset es User Usuario
::msgcat::mcset es Password Contraseña
::msgcat::mcset es {User or password not correct} {Usuario o password incorrecto}
::msgcat::mcset es All Todo
::msgcat::mcset es {Error: First users needs to be administrator or all} {Error: El primer usuario necesita ser administrador o todo}
::msgcat::mcset es {Error: user type is not correct} {Error: El tipod e usuario no es correcto}
::msgcat::mcset es {Added or modified user '%s', type='%s'} {Usuario '%s' añadido o modificado, tipo='%s'}
::msgcat::mcset es {Removed user '%s'} {Usuario '%s' quitado}
::msgcat::mcset es {Set database files for user '%s' to '%s'} {Preparar los archivo de base de datos para el usuario '%s' a '%s'}
::msgcat::mcset es {Clear database files for user '%s'} {Limpiar base de datos para el usuario '%s'}
::msgcat::mcset es {Error a restricted user cannot created directories} {Error: un usuario restringido no puede crear carpetas}
::msgcat::mcset es {Error a restricted user cannot rename databases} {Error: un usuario restringido no puede renombrar bases de datos}
::msgcat::mcset es {Error a restricted user cannot delete databases} {Error: un usuario restringido no puede borrar bases de datos}
::msgcat::mcset es {Error. File '%s' is not allowed for user '%s'} {Error: Archivo '%s' no está permitido para el usuario '%s'}
::msgcat::mcset es {Service %s started} {Servicio %s  inciado}
::msgcat::mcset es {Error starting service %s (%s)} {Error iniciando servicio %s (%s)}
::msgcat::mcset es {Error installing service (%s)} {Error instalando servicio (%s)}
::msgcat::mcset es {Service %s removed} {Servicio %s quitado}
::msgcat::mcset es {Error removing service %s (%s)} {Error quitando servicio %s (%s)}
::msgcat::mcset es Name%d Name%d
::msgcat::mcset es {Failed to source page '%s'. Page does not exist} {Falló la página fuente '%s'. La página no existe}
::msgcat::mcset es {Sending file '%s' (binary=%s) } {Enviando archivo '%s' (binary=%s)}
::msgcat::mcset es {Recieving file '%s' (binary=%s) } {Recibiendo archivo '%s' (binary=%s)}
::msgcat::mcset es {Could not add icon to icontray (%s)} {No se pudo añadir a el área de notificaciones (%s)}
::msgcat::mcset es {error: it is necessary to define application directory in -appdir} {error: es necesario definir el directorio de aplicación en -appdir}
::msgcat::mcset es {error: Server is stopped} {error: el servidor está parado}
::msgcat::mcset es {starting server at port %d} {iniciando servidor en el puerto %d}
::msgcat::mcset es {Started server at ports: %s} {Servidor iniciado en los puertos: %s}
::msgcat::mcset es {Started server at port: %s} {Servidor iniciado en el puerto: %s}
::msgcat::mcset es {Select port} {Seleccionar puerto}
::msgcat::mcset es Global Global
::msgcat::mcset es {No user '%s' found in database} {Ningún usuario '%s' encontrado en la base de datos}
::msgcat::mcset es {error: it is necessary to define one or more ports} {error: es necesario definir uno o más puertos}
::msgcat::mcset es {Image files} {Ficheros de imagen}
::msgcat::mcset es {All Files} {Todos los archivos}
::msgcat::mcset es {Add file} {Añadir archivo}
::msgcat::mcset es {Enter file name for the image} {Entrar el nombre del archivo para la imagen}
::msgcat::mcset es {Import from file} {Importar desde el archivo.}
::msgcat::mcset es {View more entries} {Ver más entradas}
::msgcat::mcset es {View end} {Ver final}
::msgcat::mcset es {View all entries} {Ver todas las entradas}
::msgcat::mcset es {Clear search entry (Backspace)} {Limpiar entrada de búsqueda (Retroceso)}
::msgcat::mcset es {Reduced view} {Vista reducida}
::msgcat::mcset es {Notes view} {Vista de notas}
::msgcat::mcset es {Draw box} {Caja de dibujo}
::msgcat::mcset es {Clear last draw box} {Limpiar la última caja de dibujo}
::msgcat::mcset es {Clear ALL draw box} {Limpiar TODAS las cajas de dibujo}
::msgcat::mcset es {Draw point (zoomed)} {Punto de dibujo (aumentado)}
::msgcat::mcset es {Draw point} {Dibujar punto}
::msgcat::mcset es Color Color
::msgcat::mcset es Reset Reinicializar
::msgcat::mcset es {other operations} {otras operaciones}
::msgcat::mcset es {Scatter plot} {Gráfico de dispersión}
::msgcat::mcset es {Edit axis} {Editar ejes}
::msgcat::mcset es Displacement Desplazamiento
::msgcat::mcset es Vector Vector
::msgcat::mcset es Functions Funciones
::msgcat::mcset es Area Área
::msgcat::mcset es {Area under a function} {Área bajo una función}
::msgcat::mcset es {Area between two functions} {Área entre 2 funciones}
::msgcat::mcset es {Area of the region enclosed by two functions} {Área de la región cerradas por dos funciones}
::msgcat::mcset es {Export to spreadsheet (XML files)} {Exportar a hoja de cálculo (archivos XML)}
::msgcat::mcset es {Import from spreadsheet (XML files)} {Importar de hoja de cálculo (archivos XML)}
::msgcat::mcset es {Save as SVG} {Guardar como SVG}
::msgcat::mcset es Legend Leyenda
::msgcat::mcset es {SVG files} {Ficheros SVG}
::msgcat::mcset es {Area between a function and the x-axis} {Área entre una función y los ejes-x}
::msgcat::mcset es {Area of the region between the x axis, the fat lines labeled a and b, and the graph.} {Área de la región entre los ejes x, las líneas gruesas llamadas a y b, y el gráfico.}
::msgcat::mcset es {The limits of integration will be the intersection points of the two curves.} {Los límites de integración serán los puntos de intersección de las dos curvas.}
::msgcat::mcset es {Integration interval:} {Intervalo de la integración:}
::msgcat::mcset es {From (a):} {De (a):}
::msgcat::mcset es {Enter the start x-coordinate 
for the range on the graph} {Entre el final de la coordenada-x 
for el rango en el gráfico}
::msgcat::mcset es {To (b):} {A (b):}
::msgcat::mcset es {Enter the end x-coordinate 
for the range on the graph} {Entre el inicio de la coordenada-x 
for el rango en el gráfico}
::msgcat::mcset es Functions: Funciones:
::msgcat::mcset es f(x) f(x)
::msgcat::mcset es {Selected functions} {Funciones seleccionadas}
::msgcat::mcset es g(x) g(x)
::msgcat::mcset es Area: Área:
::msgcat::mcset es {Calculates the area under the graph of the 
selected functions using Simpson's formula.} {Calcula el área bajo el gráfico de las funciones 
selected usando la fórmula de Simpson.}
::msgcat::mcset es u² u²
::msgcat::mcset es {Incorrect integration interval.} {Intervalo de la integración incorrecto.}
::msgcat::mcset es {Function f(x) should be different than g(x).} {La función f(x) debería ser diferente de g(x).}
::msgcat::mcset es {The functions do not intersect.} {Las funciones no se intersectan.}
::msgcat::mcset es X-value valor-X
::msgcat::mcset es {X displacement value} {Valor de desplazamiento X}
::msgcat::mcset es Y-value valor-Y
::msgcat::mcset es {Y displacement value} {valor de desplazamiento Y}
::msgcat::mcset es {Incorrect x-axis range.} {Rango de ejes-x incorrecto.}
::msgcat::mcset es {Incorrect y-axis left range.} {Rango inzquierdo de ejes-y incorrecto.}
::msgcat::mcset es {Incorrect y-axis right range.} {Rango derecho de ejes-y incorrecto.}
::msgcat::mcset es General General
::msgcat::mcset es {Automatic x-y axis} {Ejes x-y automático.}
::msgcat::mcset es {Automatic x-y axis range} {Rango de ejes x-y automático}
::msgcat::mcset es x-axis Eje-x
::msgcat::mcset es Maximum Máximo
::msgcat::mcset es {Maximum x-axis value} {Máximo valor de eje-x}
::msgcat::mcset es Minimum Mínimo
::msgcat::mcset es {Minimum x-axis value} {Mínimo valor de eje-x}
::msgcat::mcset es y-axis Eje-y
::msgcat::mcset es {Maximum y-axis value} {Máximo valor de eje-y}
::msgcat::mcset es {Minimum y-axis value} {Mínimo valor de eje-y}
::msgcat::mcset es {XML files} {Ficheros XML}
::msgcat::mcset es {Import data from spreadsheet file} {Importar datos del archivo de hoja de cálculo}
::msgcat::mcset es {File extension should be xml} {La extensión del archivo debería ser xml}
::msgcat::mcset es {Excel files} {Archivos Excel}
::msgcat::mcset es {Save graph as spreadsheet (Excel...)} {Guardar gráfico como hoja de cálculo (Excel...)}
::msgcat::mcset es {starting server at port %d. Work dir: %s} {iniciando el servidor en el puerto %d. Dir de trabajo: %s}
::msgcat::mcset es {Starting mail server at port 25} {Iniciando el correo del servidor en el puerto 25}
::msgcat::mcset es {Error starting mail server: %s} {Error inicio servidor de correo: %s}
::msgcat::mcset es {Mail server not started} {Correo del servidor no iniciado}
::msgcat::mcset es {Error inserting mail from mail_server (%s)} {Error al insertar el correo desde el mail_server (%s)}
::msgcat::mcset es Mail Correo
::msgcat::mcset es {Search mail message} {Buscar el mensaje de correo}
::msgcat::mcset es {Message id} {Mensaje id}
::msgcat::mcset es {Entered new item '%s' for diary in '%s'} {Entró '%s' nuevo elemento para el diario en '%s'}
::msgcat::mcset es Repeat Repetir
::msgcat::mcset es {Enter value} {Entrar valor}
::msgcat::mcset es value valor
::msgcat::mcset es {Set value} {Establecer valor}
::msgcat::mcset es animation animación
::msgcat::mcset es {Connection with the server has been lost (%s)} {La conexión con el servidor se ha perdido (%s)}
::msgcat::mcset es {Open new database} {Abrir nueva base de datos}
::msgcat::mcset es {Examples: word1 and word2 idx>250} {Ejemplos: palabra1 y palabra2 idx>250}
::msgcat::mcset es {Draw faces} {Dibujar caras}
::msgcat::mcset es {txt files} {Archivos txt}
::msgcat::mcset es {Save faces} {Guardar caras}
::msgcat::mcset es {Open faces} {Abrir caras}
::msgcat::mcset es {Octree not defined here} {Octree no definido aquí}
::msgcat::mcset es {Press arrows and prev/next page to move face} {Pulse flechas y página previa/siguiente para mover la cara}
::msgcat::mcset es {Press mouse-1 and move mouse to move face in XY} {Pulse ratón-1 y mueva el ratón para mover cara en XY}
::msgcat::mcset es {Press shift-mouse-1 and move mouse to move face in Z} {Pulse Mayús-ratón-1 y mueva el ratón para mover cara en Z}
::msgcat::mcset es {Press 0,1,2,3,4,5 to change face idx} {Pulse 0,1,2,3,4,5 para cambiar idx de la cara}
::msgcat::mcset es {Press 'Return' to draw face} {Pulse 'Volver' para dibujar cara}
::msgcat::mcset es {Press 's' to save faces. 'r' to recover} {Pulse 's' para guardar caras. 'r' para recuperar}
::msgcat::mcset es {Cound not open log file '%s' (%s)} {No se pudo abrir el archivo de registro '% s'  (% s)}
::msgcat::mcset es {Retrieving '%s'...} {Obteniendo '%s'...}
::msgcat::mcset es {error: could not resolve image '%s' as '%s'} {error: no se pudo resolver la imagen '% s' como '% s'}
::msgcat::mcset es {error: could not resolve image '%s'} {error: no se pudo resolver la imagen '%s'}
::msgcat::mcset es {Import from spreadsheet} {Importar de la hoja de cálculo}
::msgcat::mcset es {Microsoft Excel (.xml)(*.xml)} {Microsoft Excel (.xml)(*.xml)}
::msgcat::mcset es {Text (.csv)(*.csv)} {Texto (.csv)(*.csv)}
::msgcat::mcset es {Export to spreadsheet} {Exportar a la hoja de cálculo}
::msgcat::mcset es {GUI preferences} {Preferencias GUI}
::msgcat::mcset es {CSV files} {Ficheros CSV}
::msgcat::mcset es {Import data spreadsheet file (CSV file)} {Importar datos del archivo de la hoja de cálculo (archivo CSV)}
::msgcat::mcset es {File extension should be csv} {La extensión del archivo debe ser csv}
::msgcat::mcset es {Import data from spreadsheet file (XML file)} {Importar datos del archivo de la hoja de cálculo (archivo XML)}
::msgcat::mcset es {Save graph as spreadsheet (CSV file)} {Guardar gráfico como hoja de cálculo (archivo CSV)}
::msgcat::mcset es {Graphical appearance} {Apariencia gráfica}
::msgcat::mcset es colors colores
::msgcat::mcset es {Background color view} {Color de fondo en la visualización}
::msgcat::mcset es {Color view} {Imagen en color}
::msgcat::mcset es {Color selection} {Selección de color}
::msgcat::mcset es {Foreground color view} {Primer plano de imagen en color}
::msgcat::mcset es {Add grid lines to graph} {Añadir líneas de cuadrícula al gráfico}
::msgcat::mcset es {To control the presence and appearance of grid lines on the graph} {Controlar la presencia y la apariencia de las líneas de cuadrícula en el gráfico}
::msgcat::mcset es {Choose a %s color} {Elegir un color %s}
::msgcat::mcset es {Could not start server at port %s. (%s)} {No se pudo iniciar el servidor en el puerto% s. (%s)}
::msgcat::mcset es {Starting server at port %d. Work dir: %s} {Inicio del servidor en el puerto%d. Dir. de trabajo: %s}
::msgcat::mcset es {Executing '$args' in '$dir'} {Ejecutando '$args' en '$dir'}
::msgcat::mcset es {file exists '%s': %s} {existe el archivo '%s': %s}
::msgcat::mcset es {File '%s' is not a regular file} {El archivo '%s' no es un archivo normal}
::msgcat::mcset es {file_save_in_cache '%s'} {archivo_guardado_en_cache '%s'}
::msgcat::mcset es {Enter server password. Result=%s} {Introducir contraseña de servidor. Resultado=%s}
::msgcat::mcset es {error in retrieving info for process %s (%s)} {error al recuperar información para el proceso %s (%s)}
::msgcat::mcset es {error in retrieving info for process %s (%s)
} {error al recuperar información para el proceso %s (%s)
}
::msgcat::mcset es {error: -appdir cannot be void} {error: -appdir no puede ser nulo}
::msgcat::mcset es {Error installing service. It is necessary to be root (%s)} {Error al instalar el servicio. Es necesario ser raíz (%s)}
::msgcat::mcset es {Service %s starting at port %s. appdir=%s

%s} {Servicio %s comienza en puerto %s. appdir =%s

%s}
::msgcat::mcset es {Service %s starting at ports %s

%s} {Servicio %s comienza en puertos %s

%s}
::msgcat::mcset es {error: options -install_remote is only available for the Windows version} {error: opciones -instalación_remota sólo está disponible para Windows}
::msgcat::mcset es New#C#Masculino Nuevo
::msgcat::mcset es Activate Activar
::msgcat::mcset es Dectivate Desactivar
::msgcat::mcset es {Move up} {Mover arriba}
::msgcat::mcset es {Move down} {Mover abajo}
::msgcat::mcset es {Add row} {Añadir fila}
::msgcat::mcset es {Edit row} {Editar fila}
::msgcat::mcset es row Fila
::msgcat::mcset es all todo
::msgcat::mcset es {Import from CSV file} {Importar desde archivo CSV}
::msgcat::mcset es {Export to CSV file} {Exportar a archivo CSV}
::msgcat::mcset es {error: default values for option must be elements of the list} {error: los valores por defecto para la opción debe ser elementos de la lista}
::msgcat::mcset es {Export to CSV} {Exportar a CSV}
::msgcat::mcset es {It is necessary to select one entry in order to delete it} {Es necesario seleccionar entrada para eliminarla}
::msgcat::mcset es {Input data} {Datos de entrada}
::msgcat::mcset es {$col} {$col}
::msgcat::mcset es {options multiple editable} {opciones múltiples editables}
::msgcat::mcset es {options multiple non-editable} {opciones múltiples no editables}
::msgcat::mcset es {Data cannot be saved. It is not valid XML (%s)} {Datos no pueden ser guardados. No es válido XML (%s)}
::msgcat::mcset es {Select %s} {Seleccionar %s}
::msgcat::mcset es {Select field} {Seleccionar campo}
::msgcat::mcset es Select Seleccionar
::msgcat::mcset es {There has been a timeout in the connection} {Se ha producido un tiempo de espera en la conexión}
::msgcat::mcset es {Error checking file '%s' (%s)} {Error al comprobar archivo '%s' (%s)}
::msgcat::mcset es {Host does not have users. Create first one user} {Host no tiene usuarios. Crear primero un usuario}
::msgcat::mcset es {User is not allowed to run analysis} {El usuario no está autorizado a ejecutar el análisis}
::msgcat::mcset es {It is necessary a password to connect to host '%s'} {Es necesaria una contraseña para conectarse al host '%s'}
::msgcat::mcset es {Are you sure to unconnect from host '%s' and kill any process?} {¿Está seguro de desconectarse del host '% s' acabar cualquier proceso?}
::msgcat::mcset es {Remember password} {Recordar contraseña}
::msgcat::mcset es {Program is not running} {El programa no se ejecuta}
::msgcat::mcset es {Server password} {Contraseña del servidor}
::msgcat::mcset es {Exit after analysis} {Salir después de análisis}
::msgcat::mcset es {Server is in evaluation version mode} {El servidor está en modo evaluación}
::msgcat::mcset es {Server is in professional version mode} {El servidor está en modo profesional}
::msgcat::mcset es {Do you want to introduce a password?} {¿Quiere introducir contraseña?}
::msgcat::mcset es {Server professional mode} {Servidor modo profesional}
::msgcat::mcset es {Server does not accept passwords} {Servidor no acepta contraseña}
::msgcat::mcset es {Could not enter password in server (%s)} {No pudo entrar contraseña en servidor (%s)}
::msgcat::mcset es {Program is running} {Programa en ejecución}
::msgcat::mcset es {Connected to server '%s' - Evaluation version} {Conectado al servidor '%s'.Versión evaluación}
::msgcat::mcset es {Connected to server '%s' Professional version} {Conectado al servidor '%s'.Versión profesional}
::msgcat::mcset es {Not connected to server} {No conectado al servidor}
::msgcat::mcset es {Error retrieving server_platform (%s)} {Error al recuperar servidor_plataforma (%s)}
