#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es {Could not connect to host '%s' port '%s'} {No se pudo conectar al host '%s' puerto '%s'}
::msgcat::mcset es {Error opening file '%s' (%s)} {Error abriendo el archivo '%s' (%s)}
::msgcat::mcset es {Connection lost. Press here to retry} {Conexión  perdida. Pulse aquí para reintentar}
::msgcat::mcset es {Connection to '%s' is lost} {Se ha perdido la conexión a '%s'}
::msgcat::mcset es {Connection to '%s' is lost. Retry?} {Se ha perdido la conexión a '%s'. Reintentar?}
::msgcat::mcset es Exit Salir
::msgcat::mcset es {GiD geo files} {ficheros geo GiD}
::msgcat::mcset es {All files} {Todos los ficheros}
::msgcat::mcset es {Open GiD file} {Abrir fichero GiD}
::msgcat::mcset es {Sending file '%s' (binary=$bin) } {Enviando fichero '%s' (binario=$bin)}
::msgcat::mcset es {Recieving file '%s' (binary=$bin) } {Recibiendo fichero '%s' (binario=$bin)}
::msgcat::mcset es Deiconify Deiconificar
::msgcat::mcset es {Add user} {Añadir usuario}
::msgcat::mcset es User: Usuario:
::msgcat::mcset es Password: Contraseña:
::msgcat::mcset es {Repeat password:} {Repetir contraseña:}
::msgcat::mcset es {User type:} {Tipo de usuario:}
::msgcat::mcset es Administrator Administrador
::msgcat::mcset es Analysis Análisis
::msgcat::mcset es Database {Base de datos}
::msgcat::mcset es {Remove user} {Quitar usuario}
::msgcat::mcset es {Passwords are not equal} {Las contraseñas no son iguales}
::msgcat::mcset es {User cannot be void} {El usuario no puede estar vacio}
::msgcat::mcset es {Enter analysis password} {Introduzca contraseña de análisis}
::msgcat::mcset es {You do not have permissions to store the password} {no tiene permisos para almacenar la contraseña}
::msgcat::mcset es {Are you sure to terminate %d sessions?} {Está seguro de terminar %d sesiones?}
::msgcat::mcset es {Computer memory} {Memoria del ordenador}
::msgcat::mcset es {All processes} {Todos los procesos}
::msgcat::mcset es Memory Memoria
::msgcat::mcset es {Full memory} {Memoria completa}
::msgcat::mcset es {This process} {Este proceso}
::msgcat::mcset es {Total time} {Tiempo total}
::msgcat::mcset es {no process} {Sin proceso}
::msgcat::mcset es {Failed connection to host '%s'} {Falló la conexión al host '%s'}
::msgcat::mcset es {not connected} {no conectado}
::msgcat::mcset es {User or password not OK for host '%s'} {Usuario o contraseña incorrectos para el host '%s'}
::msgcat::mcset es {Connected to host '%s'} {Conectado al host '%s'}
::msgcat::mcset es {Are you sure to unconnect from host '$host' and kill any process?} {Está seguro de desconectarse del host '$host' y finalizar cualquier proceso?}
::msgcat::mcset es {Could not store preferences (%s)} {No se pudieron almacenar las preferencias (%s)}
::msgcat::mcset es {running on' %s'} {Corriendo '%s'}
::msgcat::mcset es {Failed running (%s)} {Fallo al correr (%s)}
::msgcat::mcset es {Compass client} {Cliente Compass}
::msgcat::mcset es Unconnect Desconectado
::msgcat::mcset es Host: Servidor:
::msgcat::mcset es Examples: Ejemplos:
::msgcat::mcset es {Password file:} {Fichero de password:}
::msgcat::mcset es {GiD model:} {modelo GiD}
::msgcat::mcset es {Select a GiD model in browser} {Selecciones un modelo GiD en el  navegador}
::msgcat::mcset es Info Información
::msgcat::mcset es Log Diario
::msgcat::mcset es {Update now} {Actualizar ahora}
::msgcat::mcset es Sessions Sesiones
::msgcat::mcset es {Server management} {Gestión del server}
::msgcat::mcset es {View remote log} {Ver diario remoto}
::msgcat::mcset es {Clear local log} {Limpiar diario local}
::msgcat::mcset es {Server version} {Versión del server}
::msgcat::mcset es Console Consola
::msgcat::mcset es {Add/remove user} {Añadir/quitar usuario}
::msgcat::mcset es {Analysis password} {Contraseña de análisis}
::msgcat::mcset es {Server version: %s} {Versión del server: %s}
::msgcat::mcset es {Could not find tkcon} {No se pudo encontrar tkcon}
::msgcat::mcset es Remote Remoto
::msgcat::mcset es {Attach to remote server} {Adjuntar al server remoto}
::msgcat::mcset es {Welcome to tkcon client console} {Bienvenido a la consola cliente tkcon}
::msgcat::mcset es {Could not find a GiD executable} {No fue posible encontrar un ejecutable de GiD}
::msgcat::mcset es {url does not begin with a known handler like: %s. Proceed?} {el url no empieza con ningún prefijo conocido: %s. ¿Continuar?}
::msgcat::mcset es Warning Atención
::msgcat::mcset es {There are %s message. Delete all of them?} {Hay %s mensajes. Borrar todos?}
::msgcat::mcset es Close Cerrar
::msgcat::mcset es Clear Limpiar
::msgcat::mcset es Save Guardar
::msgcat::mcset es {sqlite files} {ficheros sqlite}
::msgcat::mcset es {Save log} {guardar diario}
::msgcat::mcset es {sqlite3 files} {ficheros sqlite3}
::msgcat::mcset es default {Por defecto}
::msgcat::mcset es {Edit header} {Editar cabecera}
::msgcat::mcset es {Create/edit property} {Crear/editar propiedades}
::msgcat::mcset es Wizard Asistente
::msgcat::mcset es {Delete all} {Borrar todo}
::msgcat::mcset es Edit Editar
::msgcat::mcset es Copy Copiar
::msgcat::mcset es {Insert inside} {Insertar dentro}
::msgcat::mcset es {Insert before} {Insertar antes}
::msgcat::mcset es {Insert after} {Insertar después}
::msgcat::mcset es {Create drawing} {Crear dibujo}
::msgcat::mcset es Delete Borrar
::msgcat::mcset es {Edit drawing} {Editar dibujo}
::msgcat::mcset es {Ramdrawer out of sync (%s)} {Ramdrawer no está sincronizado (%s)}
::msgcat::mcset es Before Antes
::msgcat::mcset es After Después
::msgcat::mcset es Condition: Condición
::msgcat::mcset es {error: name cannot be void} {error: el nombre no puede estar vacío}
::msgcat::mcset es {error: name cannot contain 2 underlines (__)} {error: el nombre no puede contener dos guiones (__)}
::msgcat::mcset es {error: name must begin with a letter and contain letters, numbers or _ or !} {error: el nombre debe comenzar por una letra y contener letras, números o _ o !}
::msgcat::mcset es {error: expression cannot be void} {error: la expresión no puede estar vacía}
::msgcat::mcset es {error: default value for option must be one element of the list} {error: el valor por defecto para la opción debe ser un elemento de la lista}
::msgcat::mcset es {error: value must be a number} {error: el valor debe ser un número}
::msgcat::mcset es {error: name is not correct} {error: el nombre no es correcto}
::msgcat::mcset es {Change header} {Cambiar encabezado}
::msgcat::mcset es Title: Título:
::msgcat::mcset es Description: Descripción
::msgcat::mcset es Arrows Flechas
::msgcat::mcset es {Small arrows} {Flechas pequeñas}
::msgcat::mcset es Notebook {Libro de notas}
::msgcat::mcset es {Pages style:} {Estilo de páginas:}
::msgcat::mcset es {Has set name} {Tiene un set nombre}
::msgcat::mcset es {Sets are a simple way to store groups of values for latter printing in a tabular style} {Los sets son un modo simple de almacenar grupos de valores para imprimir estos últimos en un estilo tabular}
::msgcat::mcset es {Has database} {Tiene base de datos}
::msgcat::mcset es {Database name} {Nombre de la base de datos}
::msgcat::mcset es {Usable in view mode} {Usable in modo vista}
::msgcat::mcset es {Only form in view mode} {Formularios solo en el modo vista}
::msgcat::mcset es {If this option is selected, the notes part of the page is not visualized in view mode} {Si se selecciona esta opción, la parte de notas de la página no se visualiza en el modo vista}
::msgcat::mcset es {It is necessary to enter a title} {Es necesario introducir un título}
::msgcat::mcset es {It is necessary to enter a database name} {Es necesario introducir un nombre para la base de datos}
::msgcat::mcset es {Database name must only contain letters, numbers -_} {El nombre de la base de datos debe contener solo letras, números -_}
::msgcat::mcset es {Do you want to delete database '%s'?} {Desea borrar la base de datos '%s'?}
::msgcat::mcset es {Nothing to delete} {No hay nada para borrar}
::msgcat::mcset es {Are you sure to delete ALL forms information in this page?} {Está seguro de borrar TODA la información de formularios en esta página?}
::msgcat::mcset es {Change properties} {Cambiar propiedades}
::msgcat::mcset es Apply Aplicar
::msgcat::mcset es {property type} {tipo de propiedad}
::msgcat::mcset es Parameter Parámetro
::msgcat::mcset es Condition Condición
::msgcat::mcset es Container Contenedor
::msgcat::mcset es navigate navegar
::msgcat::mcset es Previous Anterior
::msgcat::mcset es Next Siguiente
::msgcat::mcset es {Go to} {Ir a}
::msgcat::mcset es Action Acción
::msgcat::mcset es New Nueva
::msgcat::mcset es {Update current} {Actualizar actual}
::msgcat::mcset es Refresh Refrescar
::msgcat::mcset es properties propiedades
::msgcat::mcset es Location: Situación:
::msgcat::mcset es {Same page} {La misma página}
::msgcat::mcset es Name: Nombre:
::msgcat::mcset es {Do you want to rename field?} {Desea renombrar el campo?}
::msgcat::mcset es {Short name:} {Nombre corto:}
::msgcat::mcset es {Print name:} {Nombre a mostrar:}
::msgcat::mcset es numeric numérico
::msgcat::mcset es text texto
::msgcat::mcset es expression expresión
::msgcat::mcset es {text expression} {expresión texto}
::msgcat::mcset es {options editable} {opciones editables}
::msgcat::mcset es {options non-editable} {opciones no editables}
::msgcat::mcset es formatted {con formato}
::msgcat::mcset es {formatted expression} {expresión con formato}
::msgcat::mcset es button botón
::msgcat::mcset es date fecha
::msgcat::mcset es {Field type:} {Campo tipo:}
::msgcat::mcset es Values: Valores:
::msgcat::mcset es {Enter a comma separator list of values here} {Introduzca una coma separador de lista de valores aquí}
::msgcat::mcset es Value: Valor:
::msgcat::mcset es Expression: Expresión:
::msgcat::mcset es Command: Comando:
::msgcat::mcset es {Examples:
\t%s} {Ejemplos:
\t%s}
::msgcat::mcset es Units: Unidades:
::msgcat::mcset es {True text:} {Texto 'cierto'}
::msgcat::mcset es {False text:} {Texto 'falso':}
::msgcat::mcset es Help Ayuda
::msgcat::mcset es {Start page} {Página de inicio}
::msgcat::mcset es {Previous page} {Página anterior}
::msgcat::mcset es {Next page} {Página siguiente}
::msgcat::mcset es {Last page} {Última página}
::msgcat::mcset es Go Ir
::msgcat::mcset es Start Inicio
::msgcat::mcset es Last Último
::msgcat::mcset es {Search in field} {Buscar en el campo}
::msgcat::mcset es {Search in any field} {Buscar en cualquier campo}
::msgcat::mcset es {Create new row} {Crear una nueva fila}
::msgcat::mcset es {Modify selected row} {Modificar la fila seleccionada}
::msgcat::mcset es {Find rows by entering text in fields} {Encontrar filas introduciendo texto en campos}
::msgcat::mcset es {Delete selected rows} {Borrar la fila seleccionada}
::msgcat::mcset es List Listar
::msgcat::mcset es {It is necessary to select one row in order to modify it} {Es necesario seleccionar una fila para modificarla}
::msgcat::mcset es {It is necessary to select only one row in order to modify it} {Es necesario elegir solo una fila para modificarla}
::msgcat::mcset es {It is necessary to select rows in order to delete them} {Es necesario seleccionar filas para borrarlas}
::msgcat::mcset es {Are you sure to delete %d rows?} {Está seguro de borrar %d filas?}
::msgcat::mcset es search buscar
::msgcat::mcset es Search Buscar
::msgcat::mcset es {Search text} {Buscar texto}
::msgcat::mcset es {Close search window} {Cerrar la ventana de búsqueda}
::msgcat::mcset es {Enter the search text in any of the fields} {Introduzca el texto a buscar en cualquiera de los campos}
::msgcat::mcset es {SQL table schema} {Esquema tabla SQL}
::msgcat::mcset es Intro Intro
::msgcat::mcset es {Update values (Return)} {Actualizar valores (Return)}
::msgcat::mcset es {Set name:} {Nombre del Set:}
::msgcat::mcset es {A set name is a way to store a group of values and results for later tabular printing} {Un Nombre de set es una forma de almacenar un grupo de valores y resultados para una posterior impresión tabular}
::msgcat::mcset es {Create new set} {Crear un nuevo set}
::msgcat::mcset es Print Imprimir
::msgcat::mcset es {Print all} {Imprimir todo}
::msgcat::mcset es {Print none} {Imprimir nada}
::msgcat::mcset es {Sets can only be modified in edit page mode} {Los sets solo pueden ser modificados en modo de edición de página}
::msgcat::mcset es {Step %d} {Paso %d}
::msgcat::mcset es {Use contextual menu (right button mouse) over the field elements in order to modify this form} {Use el menú contextual (botón derecho del ratón) sobre los elementos del campo para modificar este formulario}
::msgcat::mcset es {Select color} {Seleccionar el color}
::msgcat::mcset es {Initial value} {Valor inicial}
::msgcat::mcset es {Default value} {Valor por defecto}
::msgcat::mcset es {Select file} {Seleccionar fichero}
::msgcat::mcset es View/execute Ver/ejecutar
::msgcat::mcset es {Extract in '%s'} {Extraer en '%s'}
::msgcat::mcset es {Extract in ...} {Extraer en ...}
::msgcat::mcset es Ramviewer Ramviewer
::msgcat::mcset es {error in container '%s'. Condition not ok} {error en el contenedor '%s'. La condición no es correcta}
::msgcat::mcset es !ERROR !ERROR
::msgcat::mcset es OK#C#Valid Válido
::msgcat::mcset es {Fail#C#No Valid} {No válido}
::msgcat::mcset es {Choose Color} {Elija color}
::msgcat::mcset es {Load file} {Cargar fichero}
::msgcat::mcset es {Could not open RamViewer (%s)} {No se pudo abrir RamViewer (%s)}
::msgcat::mcset es {File: %s
} {Fichero: %s
}
::msgcat::mcset es {Size: $sizep
} {Tamaño: $sizep
}
::msgcat::mcset es {There is no file to extract} {No hay fichero a extraer}
::msgcat::mcset es {Save file} {Salvar fichero}
::msgcat::mcset es {File '%s' exists. Overwrite?} {El fichero '%s' existe. ¿Sobrescribirlo?}
::msgcat::mcset es {error: %s} {error: %s}
::msgcat::mcset es {Saved file in '%s'} {Fichero guardado en '%s'}
::msgcat::mcset es {Set %s} {Set %s}
::msgcat::mcset es {error: field '%s' not correct value='%s'} {error: campo '%s' incorrecto valor='%s'}
::msgcat::mcset es {error in field '%s' not valid value '%s'} {error en campo '%s' valor inválido '%s'}
::msgcat::mcset es {Form type} {Formulario tipo}
::msgcat::mcset es {Import data} {Importar datos}
::msgcat::mcset es {Create form fields} {Crear campos de formulario}
::msgcat::mcset es {Form created} {Formulario creado}
::msgcat::mcset es {Welcome to the forms creation wizard. Select what kind of form do you wish to create} {Bienvenido al asistente de creación de formularios. Seleccione qué tipo de formulario desea crear}
::msgcat::mcset es {A set of fields where to enter values and formulas} {Un set de campos donde introducir valores y fórmulas}
::msgcat::mcset es {A form, to store values in a database} {Un formulario, para almacenar valores en una base de datos}
::msgcat::mcset es {Enter fields definition manually} {introduzca la definición de los campos manualmente}
::msgcat::mcset es {Import from Spreadsheet (Excel or OpenOffice)} {Importar desde una hoja de cálculo (Excel u OpenOffice)}
::msgcat::mcset es {Variable names on the left} {Nombres de variables a la izquierda}
::msgcat::mcset es {View Spreadsheet variable names} {Ver nombres de variables de la Hoja de cálculo}
::msgcat::mcset es {Variable names above} {Nombres de variables arriba}
::msgcat::mcset es {Variable names above the table rows} {Nombres de variables sobre las filas de la tabla}
::msgcat::mcset es {Spreadsheet file} {Fichero de Hoja de cálculo}
::msgcat::mcset es {There has been an error when importing the Spreadsheet file (%s)} {Hubo un error al importar el fichero de Hoja de cálculo (%s)}
::msgcat::mcset es {Add fields to the form} {Añadir campos al formulario}
::msgcat::mcset es Name Nombre
::msgcat::mcset es type tipo
::msgcat::mcset es Group Grupo
::msgcat::mcset es {Field name} {Nombre del campo}
::msgcat::mcset es {default value} {valor por defecto}
::msgcat::mcset es Number Número
::msgcat::mcset es Expression Expresión
::msgcat::mcset es Add Añadir
::msgcat::mcset es {Add a new field to the form} {Añadir un nuevo campo al formulario}
::msgcat::mcset es Remove Quitar
::msgcat::mcset es {Remove the selected field from the list} {Quitar el campo seleccionado de la lista}
::msgcat::mcset es More Más
::msgcat::mcset es {Add new field in new group} {Añadir nuevo campo en nuevo grupo}
::msgcat::mcset es {Delete all fields} {Borrar todos los campos}
::msgcat::mcset es {It has not been possible to import any field from the Spreadsheet file} {No ha sido posible importar ningún campo desde el fichero de Hoja de cálculo}
::msgcat::mcset es {No field has been created} {No se ha creado ningún campo}
::msgcat::mcset es {A new form has been created with %d fields} {Ha sido creado un nuevo formulario con %d campos}
::msgcat::mcset es {A new form has been created with %d fields. %d rows have been imported} {Ha sido creado un nuevo formulario con %d campos, %d filas se han importado}
::msgcat::mcset es {You can modify any field in the form by right-clicking the mouse over it} {Puede modificar cualquier campo en el formulario haciendo click con el botón derecho del ratón sobre él}
::msgcat::mcset es {You can try with a new Spreadsheet file by pressing button 'Previous'} {Puede probar con un nuevo fichero de Hoja de Cálculo pulsando el botón 'Previo'}
::msgcat::mcset es {You can add new fields by pressing button 'Previous'} {Puede añadir nuevos campos pulsando el botón 'Previo'}
::msgcat::mcset es {Group %d} {Grupo %d}
::msgcat::mcset es {Select group} {Seleccionar grupo}
::msgcat::mcset es {Enter the name for the group where the field will be inserted:} {Introduzca el nombre del grupo donde se insertará el campo:}
::msgcat::mcset es {It is necessary to enter a field name} {Se necesita introducir un nombre de campo}
::msgcat::mcset es {A field with this name already exists} {Ya existe un campo con ese nombre}
::msgcat::mcset es {Spreadsheet files} {Ficheros de Hoja de cálculo}
::msgcat::mcset es {Import Spreadsheet file} {Importar fichero de Hoja de cálculo}
::msgcat::mcset es {It is necessary to have Excel installed in the computer. Try to import format XML-2003 or XLSX or ODS} {Se necesita tener Excel instalado en el ordenador. Intente importar el formato XML-2003 o XLSX o ODS}
::msgcat::mcset es Today Hoy
::msgcat::mcset es {starting server (version %s)} {Iniciando servidor (versión  %s)}
::msgcat::mcset es {Exiting server} {saliendo de servidor}
::msgcat::mcset es {Auto finished session %s-%s-%s-%s} {Sesión finalizada automáticamente %s-%s-%s-%s}
::msgcat::mcset es {Error restarting session '%s' (%s)} {Error reiniciando sesión '%s' (%s)}
::msgcat::mcset es {Auto restarted session %s-%s-%s-%s} {Sesión reiniciada automáticamente %s-%s-%s-%s}
::msgcat::mcset es {Lost session %s-%s-%s-%s} {Sesión perdida %s-%s-%s-%s}
::msgcat::mcset es {Ended session %s-%s-%s-%s} {Sesión terminada %s-%s-%s-%s}
::msgcat::mcset es {rejected connection} {Conexión rechazada}
::msgcat::mcset es {rejected connection from '%s' user '%s' user_type '%s'. bad username/password} {conexión rechazada desde '%s' usuario '%s' tipo_de_usuario '%s'. Mal nombre de usuario/contraseña}
::msgcat::mcset es {rejected connection. bad username/password} {Conexión rechazada. Mal nombre de usuario/contraseña}
::msgcat::mcset es {rejected connection. session does not exist} {Conexión rechazada. No existe sesión}
::msgcat::mcset es {reconnected to session '%s'} {Reconectado a sesión '%s'}
::msgcat::mcset es {accepted connection from '%s' user '%s' type '%s'. Created session '%s'} {conexión aceptada desde '%s' usuario '%s' tipo '%s'. Creada sesión '%s'}
::msgcat::mcset es {Compass server} {Servidor Compass}
::msgcat::mcset es {Clear log} {Limpiar diario}
::msgcat::mcset es {View log} {Ver diario}
::msgcat::mcset es Hide Ocultar
::msgcat::mcset es {Started server at port %s} {Servidor iniciado en puerto %s}
::msgcat::mcset es {Compass server (port: %s)} {Servidor Compass (puerto: %s)}
::msgcat::mcset es {starting icon try} {Iniciando bandeja de icono}
::msgcat::mcset es {Added user '%s', type='%s'} {Añadido usuario '%s', type='%s'}
::msgcat::mcset es {Removed user '%s' type '%s'} {Quitado usuario '%s' tipo '%s'}
::msgcat::mcset es {Creating directory '%s'} {Creando directorio '%s'}
::msgcat::mcset es {killed process %s} {Proceso eliminado %s}
::msgcat::mcset es {recieving file '%s'} {recibiendo fichero '%s'}
::msgcat::mcset es {recieved file} {fichero recibido '%s'}
::msgcat::mcset es {sending file '%s'} {enviando fichero '%s'}
::msgcat::mcset es {failed sending file '%s'} {fallo enviando fichero '%s'}
::msgcat::mcset es {Requesting sessions list} {Solicitando lista de sesiones}
::msgcat::mcset es Id Identificar
::msgcat::mcset es Username {Nombre de usuario}
::msgcat::mcset es Type Tipo
::msgcat::mcset es Connection Conexión
::msgcat::mcset es Active Activo
::msgcat::mcset es Date Fecha
::msgcat::mcset es Directories Directorios
::msgcat::mcset es Processes Procesos
::msgcat::mcset es {Requesting processes info} {Solicitando información de procesos}
::msgcat::mcset es {error: File '%s' is not a directory} {error: Fichero '%s' no es un directorio}
::msgcat::mcset es {error: File '%s' does not exist} {error: Fichero '%s' no existe}
::msgcat::mcset es {Installing on computer '%s'} {Instalando en el ordenador '%s'}
::msgcat::mcset es {Error connecting to computer '%s' with user '%s'} {Error conectando al ordenador '%s' con el usuario '%s'}
::msgcat::mcset es {Copied files to computer '%s'} {Ficheros copiados al ordenador '%s'}
::msgcat::mcset es {Started service on computer '%s'} {Servicio iniciado en el ordenador '%s'}
::msgcat::mcset es {Going to connect (%s) to computer '%s'} {Va a conectar (%s) al ordenador '%s'}
::msgcat::mcset es {Installed on computer '%s'} {Instalado en el ordenador '%s'}
::msgcat::mcset es {Install Compass server} {Instalar servidor Compass}
::msgcat::mcset es Computer Ordenador
::msgcat::mcset es Computer: Ordenador:
::msgcat::mcset es {A list of one or more computers. Examples:} {Una lista de uno o más ordenadores. Ejemplos:}
::msgcat::mcset es {Destination base dir:} {Destinación base dir:}
::msgcat::mcset es {This directory must exist} {Este directorio debe existir}
::msgcat::mcset es Server Servidor
::msgcat::mcset es {Copy local users} {Copiar usuarios locales}
::msgcat::mcset es {Service installed and running} {Servicio instalado y corriendo}
::msgcat::mcset es Icons Iconos
::msgcat::mcset es Database: {Base de datos:}
::msgcat::mcset es and y
::msgcat::mcset es or o
::msgcat::mcset es {Draw name} {dibujar nombre}
::msgcat::mcset es Search: Buscar
::msgcat::mcset es {Draw icons} {Dibujar iconos}
::msgcat::mcset es {Open new view} {Abrir nueva vista}
::msgcat::mcset es {Drop here icons for deleting them from database} {Soltar aquí los iconos para borrarlos de la base de datos}
::msgcat::mcset es {Database '%s' does not exist} {La base de datos '%s' no existe}
::msgcat::mcset es {Open database} {Abrir base de datos}
::msgcat::mcset es {user defined} {Definido por el usuario}
::msgcat::mcset es {GIF files} {ficheros GIF}
::msgcat::mcset es {Add icon} {Añadir icono}
::msgcat::mcset es {Icon name:} {Nombre del icono:}
::msgcat::mcset es {Overwrite existing icon with same name} {Sobrescribir el icono existente con el mismo nombre}
::msgcat::mcset es Collection: Colección:
::msgcat::mcset es Groups: Grupos:
::msgcat::mcset es {Are you sure to delete icon '%s'?} {Está seguro de borrar el icono '%s'?}
::msgcat::mcset es {Add icon...} {Añadir icono...}
::msgcat::mcset es {Copy name} {Copiar nombre}
::msgcat::mcset es {Copy command name} {Copiar nombre de comando}
::msgcat::mcset es {Save as...} {Salvar como...}
::msgcat::mcset es {Copy create cmd} {Copiar crear cmd}
::msgcat::mcset es Paste Pegar
::msgcat::mcset es {Delete icon} {Borrar icono}
::msgcat::mcset es {Drawing %d items} {Dibujando %d items}
::msgcat::mcset es {It is necessary to have ImageMagick installed for converting images} {Es necesario tener instalado ImageMagick para poder convertir las imágenes}
::msgcat::mcset es {Sysinfo data not correct (data='%s')} {Datos del sysinfo incorrectos (data='%s')}
::msgcat::mcset es Yes Sí
::msgcat::mcset es {Yes to all} {Sí a todo}
::msgcat::mcset es {No to all} {No a todo}
::msgcat::mcset es {Are you sure to overwrite file '%s'?} {Está seguro de sobrescribir el fichero '%s'?}
::msgcat::mcset es {Form properties} {Propiedades del formulario}
::msgcat::mcset es {Delete form} {Borrar formulario}
::msgcat::mcset es {Create/edit fields} {Crear/editar campos}
::msgcat::mcset es {Edit field} {Editar campo}
::msgcat::mcset es {Copy field} {Copiar campo}
::msgcat::mcset es {Insert field inside} {Insertar campo dentro}
::msgcat::mcset es {Insert field before} {Insertar campo antes}
::msgcat::mcset es {Insert field after} {Insertar campo después}
::msgcat::mcset es {Delete field} {Borrar campo}
::msgcat::mcset es {error: name must begin with a letter and contain letters, numbers spaces or _ or !} {error: el nombre debe empezar con una letra y contener letras, números o _ o !}
::msgcat::mcset es {Identifier '%s' is not allowed for a field name} {El identificador '%s' no está permitido para un nombre de campo}
::msgcat::mcset es {There is already a field with name '%s'. Overwrite?} {Ya hay un campo con el nombre '%s'. Sobrescribir?}
::msgcat::mcset es title título
::msgcat::mcset es Title Título
::msgcat::mcset es Description Descripción
::msgcat::mcset es {form type} {de tipo}
::msgcat::mcset es {No database} {Ninguna base de datos}
::msgcat::mcset es {The form has no associated database. Formulas can be evaluated but results sets cannot be stored} {El formulario no tiene asociada una base de datos. Pueden ser evaluadas las fórmulas, pero los resultados no se almacenarán.}
::msgcat::mcset es {The form has one associated database. Sets of values can be stored by the form user in view mode} {El formulario tiene una base de datos asociada. El set de valores pueden guardarse por el usuario del formulario en el modo de vista}
::msgcat::mcset es {Has database with named entries} {Tiene base de datos con entradas nombradas}
::msgcat::mcset es {The form has one associated database. Every stored set of values will have a name} {El formulario tiene una base de datos asociada. Cada set de valores guardados tendrá un nombre}
::msgcat::mcset es {database details} {Detalle de la base de datos}
::msgcat::mcset es Automatic Automático
::msgcat::mcset es {Hide notes in view mode} {Esconder notas en el modo vista}
::msgcat::mcset es {form style} {estilo del formulario}
::msgcat::mcset es List#C#Noun Lista
::msgcat::mcset es Buttons Botones
::msgcat::mcset es {Normal size} {Tamaño normal}
::msgcat::mcset es {Small size} {Tamaño pequeño}
::msgcat::mcset es Pages Páginas
::msgcat::mcset es {Form pages} {Páginas del formulario}
::msgcat::mcset es {Select the form page} {Seleccione la página del formulario}
::msgcat::mcset es {Name id} {Nombre id}
::msgcat::mcset es {New entry} {Nueva entrada}
::msgcat::mcset es {Modify entry} {Modificar entrada}
::msgcat::mcset es {Search in name} {Buscar en nombre}
::msgcat::mcset es {View form and database} {Ver formulario y base de datos}
::msgcat::mcset es {View database list} {Ver lista de base de datos}
::msgcat::mcset es {View form} {Ver formulario}
::msgcat::mcset es {Delete entries} {Borrar entradas}
::msgcat::mcset es {Enter the name of the entry to create or modify} {Introducir el nombre de la entrada a crear o modificar}
::msgcat::mcset es {Create new entry in the database} {Crear la nueva entrada en la base de datos}
::msgcat::mcset es {Modify selected entry in the databse} {Modificar la entrada seleccionada en la base de datos}
::msgcat::mcset es {Search database} {Buscar base de datos}
::msgcat::mcset es {Additional commands} {Comandos adicionales}
::msgcat::mcset es Page Página
::msgcat::mcset es {Database List} {Lista de base de datos}
::msgcat::mcset es {It is necessary to enter a name for the new entry} {Es necesario introducir un nombre para la nueva entrada}
::msgcat::mcset es {It is necessary to enter the name of the entry to be modified} {Es necesario introducir el nombre de la entrada a modificar}
::msgcat::mcset es {There is already one entry with name '%s'. Modify it?} {Ya hay una entrada con el nombre '%s'. Desea modificarla?}
::msgcat::mcset es {There is no entry with name '%s'. It cannot be modified} {No hay entrada con el nombre '%s'. No puede modificarse}
::msgcat::mcset es {It is necessary to select one entry in order to modify it} {Es necesario seleccionar una entrada para modificarla}
::msgcat::mcset es {It is necessary to select only one entry in order to modify it} {Es necesario seleccionar solo una entrada para modificarla}
::msgcat::mcset es {Created new entry with name '%s'} {Creada nueva entrada con nombre '%s'}
::msgcat::mcset es {Modified entry with name '%s'} {Entrada modificado con nombre '%s'}
::msgcat::mcset es {Created new entry} {Creada nueva entrada}
::msgcat::mcset es {Updated selected entry} {Actualizada entrada seleccionada}
::msgcat::mcset es {There are no entries that fullfill this search criteria} {No hay entradas que cumplan ese criterio de búsqueda}
::msgcat::mcset es {It is necessary to select one entry in order to get its values} {Es necesario seleccionar una entrada para obtener su valores}
::msgcat::mcset es {There are %d entries that fullfill this search criteria} {Hay %d entradas que cumplen este criterio de búsqueda}
::msgcat::mcset es {It is necessary to select only one entry in order to get its values} {Es necesario seleccionar solo una entrada para obtener sus valores}
::msgcat::mcset es {It is necessary to select one or more entries in order to delete them} {Es necesario seleccionar una o más entradas para borrarlas}
::msgcat::mcset es {It is necessary to enter a name for deleting its entry} {Es necesario introducir un nombre para borrar su entrada}
::msgcat::mcset es {Entry with name '%s' does not exist in the database} {La entrada con nombre '%s' no existe en la base de datos}
::msgcat::mcset es {Are you sure to delete entry '%s'?} {Está seguro de borrar la entrada '%s'?}
::msgcat::mcset es {Are you sure to delete one entry?} {Está seguro de borrar una entrada?}
::msgcat::mcset es {Are you sure to delete %d entries?} {Está seguro de borrar %d entradas?}
::msgcat::mcset es {Select file (examples directory)} {Seleccione fichero (directorio ejemplos)}
::msgcat::mcset es Reload Recargar
::msgcat::mcset es {There is no image to view} {No hay imagen que visualizar}
::msgcat::mcset es {Values by color} {Valores por color}
::msgcat::mcset es {Delete existing fields} {Borrar campos existentes}
::msgcat::mcset es Note Nota
::msgcat::mcset es {All fields need to be contained in one group. There can exist one or more groups} {Todos los campos necesitan estar contenidos en un grupo. Pueden existir uno o más grupos}
::msgcat::mcset es {It is necessary to enter a group name} {Es necesario introducir un nombre de grupo}
::msgcat::mcset es popt popt
::msgcat::mcset es {unknown errno} {unknown errno}
::msgcat::mcset es {option type (%d) not implemented in popt
} {option type (%d) not implemented in popt
}
::msgcat::mcset es {missing argument} {missing argument}
::msgcat::mcset es {unknown option} {unknown option}
::msgcat::mcset es {aliases nested too deeply} {aliases nested too deeply}
::msgcat::mcset es {error in paramter quoting} {error in paramter quoting}
::msgcat::mcset es {invalid numeric value} {invalid numeric value}
::msgcat::mcset es {number too large or too small} {number too large or too small}
::msgcat::mcset es {unknown error} {unknown error}
::msgcat::mcset es {Show this help message} {Show this help message}
::msgcat::mcset es {Display brief usage message} {Display brief usage message}
::msgcat::mcset es ARG ARG
::msgcat::mcset es Usage: Usage:
::msgcat::mcset es {[OPTION...]} {[OPTION...]}
::msgcat::mcset es {Find executable for '%s'} {Encontrar ejecutable para '%s'}
::msgcat::mcset es {Executable file} {Fichero ejecutable}
::msgcat::mcset es {TCL files} {Ficheros TCL}
::msgcat::mcset es {Find RamDebugger.tcl} {Encontrar RamDebugger.tcl}
::msgcat::mcset es {Open RamDebugger} {Abrir RamDebugger.tcl}
::msgcat::mcset es {RamDebugger cannot be open. It can be installed from http://www.compassis.com/ramdebugger.} {No puede abrirse RamDebugger. Puede instalarlo desde http://www.compassis.com/ramdebugger.}
::msgcat::mcset es {Do you want to find it manually (RamDebugger.tcl)?} {Desea encontrarlo manualmente (RamDebugger.tcl)?}
::msgcat::mcset es File Fichero
::msgcat::mcset es {RamDebugger not found} {RamDebugger no encontrado}
::msgcat::mcset es {[$node @pn } {[$node @pn}
::msgcat::mcset es {Import from other forms} {Importar desde otros formularios}
::msgcat::mcset es {Edit field '%s'} {Editar campo '%s'}
::msgcat::mcset es {Edit container '%s'} {Editar contenedor '%s'}
::msgcat::mcset es {Same line} {Misma línea}
::msgcat::mcset es {Same menu} {Mismo menú}
::msgcat::mcset es {Lognoter help:} {Ayuda Lognoter:}
::msgcat::mcset es {Use a page of current lognoter database for help} {Use una página de la actual base de datos de Lognoter para ayuda.}
::msgcat::mcset es {display style} {Mostrar estilo}
::msgcat::mcset es {Small buttons} {Botones pequeños}
::msgcat::mcset es {Detailed formulas} {Fórmulas detalladas}
::msgcat::mcset es Never Nunca
::msgcat::mcset es {When editing} {Al editar}
::msgcat::mcset es {In forms} {En formularios}
::msgcat::mcset es {In print} {En impresión}
::msgcat::mcset es Always Siempre
::msgcat::mcset es {print options} {opciones de impresión}
::msgcat::mcset es {For first data set} {Para el primer set de datos}
::msgcat::mcset es {Print detailed form} {Imprimir formulario detallado}
::msgcat::mcset es {For all data sets} {Para todos los sets de datos}
::msgcat::mcset es {Print table} {Imprimir tabla}
::msgcat::mcset es {Do not print} {No imprimir}
::msgcat::mcset es Import Importar
::msgcat::mcset es {Select form} {Seleccionar formulario}
::msgcat::mcset es Entry Entrada
::msgcat::mcset es {Page is not a correct form} {La página no es un formulario correcto}
::msgcat::mcset es {Entry is not correct} {La entrada no es correcta}
::msgcat::mcset es {Select page} {Seleccione página}
::msgcat::mcset es {Clear from list} {Limpiar de la lista}
::msgcat::mcset es {Page '%s' is not a correct form} {La página '%s' no es un formulario correcto}
::msgcat::mcset es {Do you want to delete existing table '%s'?} {Desea borrar la tabla existente '%s'?}
::msgcat::mcset es {Are you sure to delete internal database for page '%s'?} {Está seguro de borrar la base de datos interna para la página '%s'?}
::msgcat::mcset es {Are you sure to delete internal database for current page?} {Está seguro de borrar la base de datos para la página actual?}
::msgcat::mcset es {Do you want to delete database '%s' associated to page '%s'?} {Desea borrar la base de datos '%s' asociada a la página '%s'?}
::msgcat::mcset es {Do you want to delete database '%s' associated to current page?} {Desea borrar la base de datos '%s' asociada a la actual página?}
::msgcat::mcset es {Are you sure to delete all forms information in this page?} {Está seguro de borrar toda la información de los formularios en esta página?}
::msgcat::mcset es {Report maker} {Creador de informes}
::msgcat::mcset es {If condition evaluate to false or 0, field or container will be disabled.
Examples:
\t%s} {Si la condición  es falsa o 0, el campo o contenedor será deshabilitado.
Ejemplos:

t%s}
::msgcat::mcset es {Show database list} {Mostrar la lista de base de datos}
::msgcat::mcset es {Hide database list} {Esconder lista de base de datos}
::msgcat::mcset es {The form has changes in its values. Do you want to proceed and loose any modifications?} {El formulario tiene cambios en sus valores. Quiere proceder y perder cualquier modificación?}
::msgcat::mcset es {Press here to see the entries} {Pulse aquí para ver las entradas}
::msgcat::mcset es letters letras
::msgcat::mcset es {Select all} {Seleccionar todo}
::msgcat::mcset es First Primero
::msgcat::mcset es {Move entry to %s} {Mover entrada a %s}
::msgcat::mcset es {Edit subtree '%s'} {Editar subárbol '%s'}
::msgcat::mcset es {Data cannot be saved. It is out of sync} {No pueden guardarse los datos. Fuera de sincronización}
::msgcat::mcset es {Data cannot be saved. It is not correct} {No pueden guardarse los datos. No son correctos}
::msgcat::mcset es {Data cannot be saved. It is not valid XML ($newNode)} {No pueden guardarse los datos. No es un XML válido ($newNode)}
::msgcat::mcset es {Data cannot be saved. It is not OK} {No pueden guardarse los datos. Incorrectos.}
::msgcat::mcset es {Actualize formulae values (Return)} {Actualizar los valores de formula (Return)}
::msgcat::mcset es Actualize Actualizar
::msgcat::mcset es {Import data from other forms} {Importar datos desde otros formularios}
::msgcat::mcset es {It is not possible to visualize help for page '%s'} {No es posible visualizar la ayuda para la página '%s'}
::msgcat::mcset es {error in field '%s'. Condition not ok} {Error en el campo '%s'. Condición incorrecta}
::msgcat::mcset es {I shall create it by myself} {Lo crearé yo mismo}
::msgcat::mcset es Numeric Numérico
::msgcat::mcset es {Edit the selected field of the form} {Editar el campo seleccionado del formulario}
::msgcat::mcset es {Add new field in new container} {Añadir un nuevo campo en el nuevo contenedor}
::msgcat::mcset es {Edit field in new container} {Editar campo en el nuevo contenedor}
::msgcat::mcset es {It is necessary to select one field in the list} {Se necesita seleccionar un campo en la lista}
::msgcat::mcset es {Container %d} {Contenedor %d}
::msgcat::mcset es {Select container} {Seleccione contenedor}
::msgcat::mcset es {Enter the name for the container where the field will be inserted:} {Introduzca el nombre para el contenedor donde se insertará el campo:}
::msgcat::mcset es {All fields need to be contained in one container. There can exist one or more containers} {Todos los campos necesitan estar dentro de un contenedor. Pueden existir uno o más contenedores.}
::msgcat::mcset es {It is necessary to enter a container name} {Es necesario introducir un nombre de contenedor}
::msgcat::mcset es {The value for a numeric field needs to be a number} {El valor para un campo numérico debe ser un número.}
::msgcat::mcset es {The value for a expression field cannot be void} {El valor para un campo de expresión no puede estar vacio}
::msgcat::mcset es {It is necessary to enter a file name} {Es necesario introducir un nombre de fichero.}
::msgcat::mcset es {File '%s' does not exist} {El fichero '%s' no existe.}
::msgcat::mcset es OK Aceptar
::msgcat::mcset es Cancel Cancelar
::msgcat::mcset es {Select the page} {Seleccione la página}
::msgcat::mcset es {Add title page} {Añadir página de título}
::msgcat::mcset es {Add normal page} {Añadir página normal}
::msgcat::mcset es {Page %d} {Página %d}
