#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es Edit Editar
::msgcat::mcset es After Después
::msgcat::mcset es Before Antes
::msgcat::mcset es Expression: Expresión:
::msgcat::mcset es Condition: Condición
::msgcat::mcset es {error: name cannot be void} {error: el nombre no puede estar vacío}
::msgcat::mcset es {error: expression cannot be void} {error: la expresión no puede estar vacía}
::msgcat::mcset es {error: name is not correct} {error: el nombre no es correcto}
::msgcat::mcset es {Change properties} {Cambiar propiedades}
::msgcat::mcset es New Nueva
::msgcat::mcset es Delete Borrar
::msgcat::mcset es {property type} {tipo de propiedad}
::msgcat::mcset es Parameter Parámetro
::msgcat::mcset es Condition Condición
::msgcat::mcset es Container Contenedor
::msgcat::mcset es navigate navegar
::msgcat::mcset es Previous Anterior
::msgcat::mcset es Next Siguiente
::msgcat::mcset es {Go to} {Ir a}
::msgcat::mcset es {Update current} {Actualizar actual}
::msgcat::mcset es Refresh Refrescar
::msgcat::mcset es properties propiedades
::msgcat::mcset es Location: Situación:
::msgcat::mcset es Name: Nombre:
::msgcat::mcset es {Short name:} {Nombre corto:}
::msgcat::mcset es {Print name:} {Nombre a mostrar:}
::msgcat::mcset es Units: Unidades:
::msgcat::mcset es {True text:} {Texto 'cierto'}
::msgcat::mcset es {False text:} {Texto 'falso':}
::msgcat::mcset es Help Ayuda
::msgcat::mcset es Start Inicio
::msgcat::mcset es Last Último
::msgcat::mcset es Go Ir
::msgcat::mcset es Intro Intro
::msgcat::mcset es {Update values (Return)} {Actualizar valores (Return)}
::msgcat::mcset es Accept Aceptar
::msgcat::mcset es Print Imprimir
::msgcat::mcset es {Print all} {Imprimir todo}
::msgcat::mcset es {Print none} {Imprimir nada}
::msgcat::mcset es {Step %d} {Paso %d}
::msgcat::mcset es {error in container '%s'. Condition not ok} {error en el contenedor '%s'. La condición no es correcta}
::msgcat::mcset es {Load case %s} {Caso de carga %s}
::msgcat::mcset es Close Cerrar
::msgcat::mcset es {Error: could not open temporal file} {Error: no se pudo abrir un fichero temporal}
::msgcat::mcset es {Table of Contents} {Tabla de contenidos}
::msgcat::mcset es OK Aceptar
::msgcat::mcset es Fail {No cumple}
::msgcat::mcset es {SVG window} {Ventana SVG}
::msgcat::mcset es OK#C#Correct Correcto
::msgcat::mcset es {Fail#C#No correct} Incorrecto
::msgcat::mcset es {Examples:
\t%s} {Ejemplos:
\t%s}
::msgcat::mcset es !ERROR !ERROR
::msgcat::mcset es OK#C#Valid Válido
::msgcat::mcset es {Fail#C#No Valid} {No válido}
::msgcat::mcset es Copy Copiar
::msgcat::mcset es {Insert before} {Insertar antes}
::msgcat::mcset es {Insert after} {Insertar después}
::msgcat::mcset es {Change header} {Cambiar encabezado}
::msgcat::mcset es Title: Título:
::msgcat::mcset es Description: Descripción
::msgcat::mcset es {Has loadcase name} {Tiene casos de carga}
::msgcat::mcset es {It is necessary to enter a title} {Es necesario introducir un título}
::msgcat::mcset es {Nothing to delete} {No hay nada para borrar}
::msgcat::mcset es {Are you sure to delete ALL formulae information?} {¿Está seguro de borrar TODA la información de fórmulas?}
::msgcat::mcset es Apply Aplicar
::msgcat::mcset es {Load case:} {Caso de carga:}
::msgcat::mcset es {Create/edit property} {Crear/editar propiedades}
::msgcat::mcset es {Delete all} {Borrar todo}
::msgcat::mcset es Action Acción
::msgcat::mcset es {Create drawing} {Crear dibujo}
::msgcat::mcset es {Edit drawing} {Editar dibujo}
::msgcat::mcset es {Ramdrawer out of sync (%s)} {Ramdrawer no está sincronizado (%s)}
::msgcat::mcset es Expression/value: Expresión/valor:
::msgcat::mcset es {Usable in view mode} {Usable in modo vista}
::msgcat::mcset es {Are you sure to delete ALL formulae information in this page?} {¿Está seguro que desea borrar toda la información de fórmulas en esta página?}
::msgcat::mcset es {Zoom in} {Zoom aumentar}
::msgcat::mcset es {Zoom out} {Zoom disminuir}
::msgcat::mcset es {Zoom last} {Zoom último}
::msgcat::mcset es {Zoom frame} {Zoom encuadrar}
::msgcat::mcset es {Select a rectangle in the screen} {Seleccione un rectángulo en la pantalla}
::msgcat::mcset es {Parameter '%s' does not exist} {El parámetro '%s'  no existe}
::msgcat::mcset es {Start page} {Página de inicio}
::msgcat::mcset es {Previous page} {Página anterior}
::msgcat::mcset es {Next page} {Página siguiente}
::msgcat::mcset es {Last page} {Última página}
::msgcat::mcset es {Play again} {Reproducir de nuevo}
::msgcat::mcset es {Stop animation} {Parar animación}
::msgcat::mcset es Message Mensaje
::msgcat::mcset es {OK to all} {Aceptar todo}
::msgcat::mcset es {Stop at user demand} {Cancelación por requerimiento del usuario}
::msgcat::mcset es {Print PNG} {Imprimir PNG}
::msgcat::mcset es Automatic Automático
::msgcat::mcset es {Stop animation (space)} {Detener animación (barra espacio)}
::msgcat::mcset es {Continue animation (space)} {Continuar animación (barra espacio)}
::msgcat::mcset es {Print PDF} {Imprimir PDF}
::msgcat::mcset es {Print image} {Imprimir imagen}
::msgcat::mcset es {Save SVG file} {Guardar el fichero SVG}
::msgcat::mcset es {Trying to go to link '%s'} {Intentando ir al link '%s'}
::msgcat::mcset es {SVG files} {Ficheros SVG}
::msgcat::mcset es {All files} {Todos los ficheros}
::msgcat::mcset es Rewind Rebobinar
::msgcat::mcset es Stop Detener
::msgcat::mcset es {Print GiD} {Imprimir GiD}
::msgcat::mcset es {Save Word file} {Guardar fichero Word}
::msgcat::mcset es Chapters Capítulos
::msgcat::mcset es Pag. Pág.
::msgcat::mcset es {Title page} {Página título}
::msgcat::mcset es {Could not open file '%s' (%s')} {No se pudo abrir el fichero '%s' (%s')}
::msgcat::mcset es Open Abrir
::msgcat::mcset es Repen Repen
::msgcat::mcset es {XML files} {Ficheros XML}
::msgcat::mcset es {Export XML file} {Exportar archivo XML}
